import { Header, Footer, JsonLd } from '../components';
import { site, staffingOffer, leadQuestions, staffingFitNote } from '../data';
export const metadata = { title: `Contact ${site.brand}`, description: 'Request a Philippines staffing plan. Share the role, tasks, tools, schedule, and quality needs.' };
export default function Contact() {
 const siteAny = site as any;
 const siteUrl = siteAny.url || `https://${String(site.domain).toLowerCase()}`;
 const schema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'ContactPage', name: `Contact ${site.brand}`, url: `${siteUrl}/contact` }, { '@type': 'Organization', name: site.brand, url: siteUrl }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Contact', item: `${siteUrl}/contact` }] }] };
 return <><Header/><main className="section"><JsonLd data={schema} /><div className="container two"><div><p className="eyebrow">Philippines staffing intake</p><h1>Plan a role for Filipino talent</h1><p className="lead">Tell us which work needs an owner. Include the tools, schedule, and decisions that must stay with your manager. Those details give a Philippines staffing team a real role to assess.</p><div className="card"><h2>What a Philippines staffing team can help map</h2><ul className="list">{staffingOffer.included.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="card"><h2>Questions that make the plan better</h2><ul className="list">{leadQuestions.map((q)=><li key={q}>{q}</li>)}</ul></div><p className="callout"><b>Philippines-only sourcing:</b> {staffingFitNote}</p></div><form className="card" action="/thank-you"><label>Name<br/><input required name="name" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Email<br/><input required name="email" type="email" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Company / website<br/><input name="company" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>What role or work do you want staffed in the Philippines?<br/><textarea name="tasks" rows={6} style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>What matters most?<br/><select name="concern" style={{width:'100%', padding:12, margin:'6px 0 14px'}}><option>Finding the right Filipino staff member</option><option>Quality control and reporting</option><option>Coverage, schedule, and time zone</option><option>Tool access and data safety</option><option>Growing a Philippines team</option></select></label><p className="oe-disclosure">Submitting this form allows follow-up about a Philippines staffing plan. Your request may be routed to a Philippines staffing partner.</p><button className="btn" type="submit">Request staffing plan</button></form></div></main><Footer/></>;
}
