export type August19BlogPost = {
  slug: string; title: string; excerpt: string; minutes: number;
  publishedDate: '2026-08-19'; body: readonly string[];
};

type Topic = { slug: string; title: string; excerpt: string; work: string; example: string; boundary: string; measure: string };

const topics: readonly Topic[] = [
  ['employee-request-decision-log','Philippines Employee Request Decision Log','Keep employee requests separate from decisions so a Philippines-based support role can prepare a trustworthy history.','employee request intake and decision logging','a schedule-change request that needs manager approval','policy interpretation and employment action','open requests by owner and age'],
  ['hr-case-evidence-index','Philippines HR Case Evidence Index','Index HR case evidence by source and date without turning an administrator into an investigator.','HR case evidence indexing','a reported workplace concern with several attachments','findings, interviews, and corrective action','source links and missing-evidence flags'],
  ['new-hire-probation-review-calendar','Philippines New-Hire Probation Review Calendar','Coordinate probation review dates while the manager retains feedback, assessment, and employment decisions.','probation review coordination','a review due after a new hire reaches a stated milestone','performance judgment and employment status','reviews completed by stage and owner'],
  ['employment-policy-version-register','Philippines Employment Policy Version Register','Prevent outdated guidance from entering employee-support workflows with a simple version register.','policy version registration','two versions of a leave or attendance guide','legal interpretation and policy approval','active version and acknowledgement state'],
  ['employee-data-retention-review','Philippines Employee Data Retention Review','Prepare retention reviews for employee records without deciding legal retention periods from guesswork.','employee-data retention review','an old document whose retention owner is unclear','legal advice, deletion approval, and exceptions','records reviewed with owner outcomes'],
  ['hr-service-request-duplicate-check','Philippines HR Service Request Duplicate Check','Reduce duplicate handling by linking related employee requests while preserving the original record.','HR service-request duplicate checking','two tickets about the same missing employment document','closing, merging, or changing the authoritative record','duplicates linked and unresolved work preserved'],
  ['remote-employee-emergency-contact-update','Philippines Remote Employee Emergency Contact Update','Coordinate emergency-contact updates with confirmation and restricted access.','emergency-contact administration','an employee submits a new contact through an approved channel','validating personal relationships or making assumptions','confirmed changes and unresolved confirmations'],
  ['employment-change-effective-date-check','Philippines Employment Change Effective-Date Check','Catch date conflicts before an approved employment change reaches downstream records.','employment-change effective-date checking','a role or schedule change with different dates in two systems','approving the change or interpreting the contract','conflicts resolved before implementation'],
  ['hr-employee-communication-archive','Philippines HR Employee Communication Archive','Archive employee communications so the source, audience, and follow-up remain reviewable.','employee communication archiving','a manager sends a notice followed by individual questions','deciding what the communication means or promising an outcome','messages archived with scope and owner'],
  ['philippines-staffing-vendor-record-review','Philippines Staffing Vendor Record Review','Review staffing-vendor records by obligation and owner without relying on sales summaries.','staffing-vendor record review','a provider change notice affecting a support role','contract interpretation and vendor approval','obligations with evidence and next dates'],
  ['employee-schedule-change-register','Philippines Employee Schedule Change Register','Track schedule changes from request through approval and implementation.','employee schedule-change registration','a recurring shift change with a one-day exception','approving schedules or deciding pay treatment','changes with effective and confirmation dates'],
  ['hr-document-access-request-review','Philippines HR Document Access Request Review','Route document-access requests through purpose, scope, and owner review.','HR document access review','a manager asks for a restricted employee file','granting access or deciding confidentiality','requests approved, denied, or awaiting owner'],
  ['philippines-recruiting-interview-feedback-index','Philippines Recruiting Interview Feedback Index','Make interview feedback easier to reconcile without ranking candidates on incomplete records.','recruiting interview-feedback indexing','three interviewers submit notes in different formats','selection decisions and candidate evaluation','submitted feedback by stage and reviewer'],
  ['employee-onboarding-identity-checklist','Philippines Employee Onboarding Identity Checklist','Coordinate identity-related onboarding evidence with a narrow checklist and explicit owner review.','onboarding identity checklist','a new hire has supplied documents through the approved route','eligibility determinations and document authenticity decisions','required items and reviewer status'],
  ['hr-absence-coverage-handoff','Philippines HR Absence Coverage Handoff','Hand off recurring HR work when an owner is absent without broadening access or authority.','HR absence-coverage handoff','a leave request queue during a manager’s absence','policy exceptions and sensitive employee decisions','open work with backup ownership'],
  ['employee-benefit-change-evidence-log','Philippines Employee Benefit Change Evidence Log','Record benefit-change evidence separately from eligibility and plan decisions.','benefit-change evidence logging','an employee reports a life event and asks what happens next','eligibility interpretation and enrollment approval','evidence received and owner response'],
  ['remote-employee-device-return-log','Philippines Remote Employee Device Return Log','Coordinate device returns at offboarding with custody evidence and exception handling.','remote device-return logging','a departing worker ships equipment from a remote location','security disposition and replacement liability','assets with custody confirmation'],
  ['employment-record-correction-register','Philippines Employment Record Correction Register','Make corrections traceable without overwriting the source record or choosing a value without authority.','employment-record correction registration','a name or start-date mismatch across approved systems','deciding the authoritative value','corrections approved and confirmed'],
  ['hr-manager-review-packet','Philippines HR Manager Review Packet','Prepare a compact review packet that lets an owner decide without searching several queues.','HR manager review-packet preparation','a weekly packet of unresolved employee requests','making the decision or hiding inconvenient evidence','packet completeness and decision latency'],
  ['philippines-staffing-role-exit-checklist','Philippines Staffing Role Exit Checklist','Close a Philippines staffing role with a visible work, access, and records checklist.','staffing-role exit coordination','a role ends while several recurring queues remain open','termination decisions and legal advice','exit items confirmed by owner'],
  ['employee-record-source-map','Philippines Employee Record Source Map','Show which source controls each employee-record field before reconciliation begins.','employee-record source mapping','an address, manager, or status appears differently across systems','choosing a source by convenience','fields mapped with effective dates'],
  ['remote-support-quality-review','Philippines Remote Support Quality Review','Review recurring Philippines-based support work with evidence, corrections, and clear manager ownership.','remote support quality review','a sample of completed employment-administration tasks','discipline, compensation, and unsupported conclusions','sample accuracy and correction themes'],
].map(([slug,title,excerpt,work,example,boundary,measure])=>({slug,title,excerpt,work,example,boundary,measure}));

const makeBody = (t: Topic, n: number): readonly string[] => [
  `${t.title} addresses a narrow operating problem in Philippines-based employment support: ${t.work}. The useful starting point is not a new tool or a broad promise. It is a written record of the trigger, the source information, the expected next action, and the person who owns the decision. A support specialist can prepare that record, but the employer or designated manager must retain authority over employment policy, sensitive employee matters, and exceptions.`,
  `Begin with a real scenario such as ${t.example}. Describe what arrived, where it was received, what fields are required, and what a complete handoff looks like. If the request lacks a date, source, employee reference, or stated question, record the gap rather than filling it with an assumption. This makes the queue useful to a Philippines-based coordinator and gives the reviewing manager a precise question to answer.`,
  `Separate preparation from judgment. The specialist may sort an intake, compare two approved records, draft a reminder, or attach evidence. The owner decides ${t.boundary}. That split should appear in the role brief, the checklist, and the review notes. A label such as “HR support” is too vague when a routine update sits next to a decision that could affect an employee.`,
  `Design the record around events instead of one editable status. Capture when the request arrived, who prepared it, what source was checked, what question was escalated, and when the owner responded. Keep the original request linked to later corrections. This prevents a neat final row from hiding a missing approval, an overwritten value, or a delay that should be addressed in the workflow.`,
  `Use the least access that allows the first task. Named accounts, multifactor authentication, restricted employee files, and an approved place for sensitive attachments are practical starting controls. A coordinator should see the queue fields needed for follow-up, while the manager and system owner control access grants, exports, deletions, and confidential notes. Review permissions when the role or task changes.`,
  `Create a small work sample before moving the whole queue. Include one ordinary request, one incomplete request, and one conflict between sources. Ask the specialist to show the prepared record, the evidence trail, and the escalation message. Review accuracy, completeness, clarity, and restraint. A fast answer that crosses the stated boundary is not a successful sample.`,
  `Set a review rhythm that matches the risk. New or sensitive work may need same-day owner review; a stable administrative queue may use a weekly sample. The review should examine ${t.measure}, plus unresolved items, repeated questions, and access exceptions. Write corrections as reusable guidance and update the example record so tomorrow’s work does not depend on memory.`,
  `Use explicit states such as received, being checked, waiting for source, waiting for owner, approved, implemented, and closed. Each state needs a next action and named owner. Do not close an item because a reminder was sent. Do not mark an approved request implemented until the downstream record or confirmation is present. These distinctions are especially important when a Philippines-based team works across time zones.`,
  `Plan the exception path before launch. If a source conflicts, the employee adds sensitive context, a deadline is missed, or the request falls outside the role, the specialist should know where to stop. The escalation message can contain the minimum useful facts, the decision requested, the deadline, and the evidence location. The owner then records the decision and any conditions.`,
  `Measure the workflow for learning rather than for unsupported performance claims. Count open items by state, time waiting for an owner, rework caused by missing instructions, and recurring source conflicts. Review a sample of outcomes with the manager. These signals can show where the process needs clarification, but they do not by themselves prove an employee’s performance, compliance, or legal position.`,
  `At the end of the first month, compare the written scope with the work actually requested. Narrow the queue if it has drifted into ${t.boundary}; add a related task only after the owner approves the change, training, evidence standard, and access. Preserve the old version of the role brief and record the effective date of the new one.`,
  `A durable handoff leaves the next person with the source map, current queue, open decisions, access owner, review cadence, and stop rules. For ${t.work}, success is not that every question disappears. It is that routine preparation moves predictably, sensitive decisions reach the right owner, and the record explains what happened without inventing facts.`,
];

export const august19BlogBatch: readonly August19BlogPost[] = topics.map((t, index) => ({
  slug: t.slug, title: t.title, excerpt: t.excerpt, minutes: 9, publishedDate: '2026-08-19', body: makeBody(t, index),
}));
