export type August20BlogPost = { slug:string; title:string; excerpt:string; minutes:number; publishedDate:'2026-08-20'; body:readonly string[] };

type Topic = { slug:string; title:string; question:string; scenario:string; lane:string; owner:string; signal:string; decision:string };

const makeBody = (t:Topic):readonly string[] => [
`August 20, 2026. ${t.title} addresses a practical question in Philippines-based outsourced employment support: ${t.question} The answer begins with a bounded administrative lane, a named source of truth, and an owner who can decide when the facts are incomplete. A support specialist can prepare information and keep a queue moving; that preparation is not a substitute for employment, legal, payroll, or policy judgment.`,
`Start with the work event rather than the job title. In this case, ${t.scenario} Record when the request arrived, what outcome was asked for, which source supplied it, and what is missing. This makes the work understandable to a Philippines-based specialist and gives the manager a short path to review. Never invent an effective date, employee fact, approval, or outcome to make a record look finished.`,
`Write the lane in one sentence: the specialist prepares ${t.lane}; ${t.owner} retains the consequential decision. That sentence should appear in the role brief, queue instructions, and review checklist. It prevents ordinary administration from expanding silently into a promise, exception, classification decision, disciplinary conclusion, or change to an employee record that the support role is not authorized to make.`,
`A useful intake record has a request reference, received date and time, employee or role reference where appropriate, requested action, source link, sensitivity flag, current state, named owner, and next review date. “Not supplied” is more truthful than a blank that looks forgotten. If the request includes sensitive detail, keep the operational queue to the minimum necessary summary and link to the approved restricted location.`,
`Use states that describe the next action: received, checking, waiting for source, waiting for owner, approved, implemented, and closed. A reminder is not approval. An approval is not proof that a system was updated. The specialist can move an item between states when the evidence supports it, while ${t.owner} confirms the decision and the system owner confirms implementation.`,
`Build a source map before access is opened. For each important field, identify the approved document or system, the person who may change it, and the evidence that confirms a change. If two sources disagree, preserve both references and describe the difference neutrally. Do not choose the convenient value, infer which version is newer, or treat a manager’s informal message as a completed instruction.`,
`The first work sample should contain an ordinary item, an incomplete item, and a conflict. Ask the candidate or specialist to prepare the record, identify the missing fact, write one escalation question, and state where they stop. Review source discipline, accuracy, completeness, privacy restraint, and clarity. Speed matters only after the sample proves the person understands the boundary.`,
`For ${t.lane}, an escalation should be short enough to answer. State what arrived, list the sources checked, name the conflict or gap, identify ${t.owner}, and give the relevant deadline. Ask one decision question. Do not diagnose the employee, promise a result, or write “handled” when the underlying owner decision is still open. A precise question is a useful output of outsourced employment support.`,
`Access should follow the first approved task, not a future wish list. Use named accounts, multifactor authentication where available, least privilege, and a documented review date. If a queue expands, reassess access instead of leaving broad permissions in place. Record who owns the grant, what event triggers removal, and where an access exception is routed.`,
`Communication design matters across time zones. Choose one queue for work, one approved channel for sensitive questions, and one place for reusable corrections. Put the source link and requested decision in each escalation. Avoid copying an entire employee history into a message when two facts and a controlled reference are enough. Good handoffs reduce waiting without turning a support role into an unauthorized decision-maker.`,
`Review completed work against the source, not against confidence or polished language. For ${t.signal}, sample enough ordinary and unusual items to see whether the right source was used, the next owner was clear, and the record could be reconstructed later. Record corrections as examples. A correction is useful when it explains what changed, who confirmed it, and how the next similar item should be routed.`,
`Do not let a dashboard turn activity into a quality claim. Counts can show queue volume, waiting items, missing fields, rework, and unresolved conflicts. They cannot establish that an employee performed poorly, that a provider achieved a business result, or that an employment obligation was satisfied. Use the signals to find unclear instructions and overloaded reviewers, then inspect the underlying examples.`,
`A manager review should end with one of three outcomes: approve the prepared action, return it with a specific correction, or escalate it to another authorized owner. Write the outcome, conditions, effective date if actually supplied, and evidence location. Keep the original request and prior values visible. This protects the audit trail and helps a Philippines-based specialist learn without rewriting history.`,
`If the queue begins to include ${t.decision}, stop and reset the scope. The specialist may gather the approved facts and show the unresolved question, but should not make the call merely because the task is urgent or the manager is unavailable. A backup owner can be named in advance. If no authorized owner is available, the correct status is waiting for owner, not completed.`,
`After the first review cycle, compare requested work with the written role. Ask which tasks were routine, which needed repeated clarification, and which crossed the boundary. Expansion requires new examples, training, access review, an owner, and an effective date. Preserve the earlier scope version so the employer can see when responsibility changed and why.`,
`A practical handoff packet for ${t.title} includes the current queue, source map, open questions, review cadence, access owner, backup path, and examples of stop conditions. Keep sensitive material in its approved location. The packet should let another authorized person understand what happened without pretending that a missing fact has been resolved or that a draft is an approved employment action.`,
`Use a short weekly review for a stable lane and a faster owner review for time-bound or sensitive items. Discuss ${t.signal}, repeated questions, source conflicts, aging work, and permission exceptions. End with named actions and dates. The review is successful when the next queue item becomes easier to handle, not when it produces a flattering but unsupported summary of people or providers.`,
`When a source is corrected, append the confirming evidence and record who made the correction. Do not silently replace the prior value. If a request is withdrawn, retain the withdrawal reference and close only the work that is genuinely finished. The same discipline applies when a worker changes role, a manager changes, or a provider hands the lane to another Philippines-based specialist.`,
`Before publishing or sharing a process guide, remove invented company details, locations, credentials, testimonials, results, prices, and promises. Explain the workflow and its limits. Readers comparing outsourced employment options need to know who prepares, who reviews, who decides, and what evidence remains. Those boundaries are more useful than a generic claim that support is simple or automatic.`,
`The durable standard is straightforward: routine work is visible, sources are controlled, uncertainty is surfaced, and the authorized employer owner makes the consequential call. For ${t.title}, begin with one queue, one reviewer, and the three-part work sample. Expand only after the record is accurate and the stop rules are understood. That is how daily Philippines-based employment administration becomes reviewable without hiding risk or overstating what the support role can do.`
];

const topics:readonly Topic[] = [
{slug:'philippines-employee-question-routing',title:'Philippines Employee Question Routing',question:'how should employee questions reach the right owner without losing context',scenario:'an employee sends a schedule question with an attachment but no requested effective date',lane:'employee-question intake and routing',owner:'the designated employment manager',signal:'unassigned questions and missing fields',decision:'interpreting policy or promising an employee outcome'},
{slug:'philippines-onboarding-document-reconciliation',title:'Philippines Onboarding Document Reconciliation',question:'how can onboarding support reconcile documents without approving an incomplete file',scenario:'a supplied onboarding document uses a different name format from the approved record',lane:'onboarding document comparison and follow-up',owner:'the onboarding decision owner',signal:'missing documents and unresolved source differences',decision:'accepting an exception or changing a required document rule'},
{slug:'philippines-schedule-change-coordination',title:'Philippines Schedule Change Coordination',question:'what evidence should a scheduling coordinator prepare before a change is applied',scenario:'a recurring shift request includes an unapproved exception and a date that conflicts with the roster',lane:'schedule-change preparation and confirmation',owner:'the schedule approver',signal:'date conflicts and pending confirmations',decision:'approving coverage, overtime, or an attendance exception'},
{slug:'philippines-payroll-input-review',title:'Philippines Payroll Input Review',question:'how can payroll support improve input quality while payment authority stays with the employer',scenario:'a manager submits a correction request without identifying the approved source or pay period',lane:'payroll-input checking and evidence assembly',owner:'the payroll owner',signal:'returned inputs and unresolved pay-period questions',decision:'pay, eligibility, deduction, or correction approval'},
{slug:'philippines-employee-record-field-mapping',title:'Philippines Employee Record Field Mapping',question:'how should a support role map fields between systems without changing the record of truth',scenario:'a manager, address, and status field differ across two approved systems',lane:'field mapping, comparison, and conflict logging',owner:'the system-of-record owner',signal:'unmapped fields and conflicting values',decision:'selecting the authoritative value or changing employment status'},
{slug:'philippines-benefits-request-intake',title:'Philippines Benefits Request Intake',question:'how can benefits administration make requests complete without deciding eligibility',scenario:'an employee reports a life event and asks what evidence is needed next',lane:'benefits request intake and approved-source tracking',owner:'the benefits decision owner',signal:'missing evidence and owner response time',decision:'eligibility, enrollment, or exception determination'},
{slug:'philippines-performance-review-coordination',title:'Philippines Performance Review Coordination',question:'what can a coordinator prepare before a manager conducts a performance review',scenario:'a review milestone is approaching while feedback is stored in three different locations',lane:'review-calendar coordination and evidence assembly',owner:'the manager responsible for the review',signal:'missing reviewers and overdue milestones',decision:'evaluating performance or setting a consequential employment action'},
{slug:'philippines-employee-access-removal-handoff',title:'Philippines Employee Access Removal Handoff',question:'how should offboarding support document access work without granting or disabling accounts itself',scenario:'a role ends while a shared mailbox and several open work items remain',lane:'offboarding checklist preparation and confirmation tracking',owner:'the employer offboarding owner',signal:'unconfirmed access actions and reassigned work',decision:'termination, emergency access, or system disablement'},
{slug:'philippines-hr-policy-version-check',title:'Philippines HR Policy Version Check',question:'how can a support role prevent stale guidance from entering an employment queue',scenario:'a new attendance document arrives while an older version remains in a shared folder',lane:'policy-source indexing and version conflict escalation',owner:'the policy approver',signal:'version conflicts and acknowledgement gaps',decision:'interpreting policy or deciding which rule applies'},
{slug:'philippines-candidate-interview-note-handoff',title:'Philippines Candidate Interview Note Handoff',question:'what should recruiting support preserve before a hiring manager reviews candidate notes',scenario:'three interviewers submit feedback in different formats and one score is missing its rationale',lane:'interview-note normalization and missing-feedback follow-up',owner:'the hiring manager',signal:'missing reviewers and unsupported scores',decision:'selecting a candidate or making a hiring judgment'},
{slug:'philippines-employee-absence-record-review',title:'Philippines Employee Absence Record Review',question:'how can absence administration surface incomplete records without diagnosing a person or deciding discipline',scenario:'an absence entry has a date but no approved source or owner confirmation',lane:'absence-record comparison and question routing',owner:'the authorized attendance owner',signal:'unmatched dates and unresolved approvals',decision:'excusing an absence, applying policy, or taking disciplinary action'},
{slug:'philippines-remote-equipment-return-coordination',title:'Philippines Remote Equipment Return Coordination',question:'what evidence makes a remote equipment handoff reviewable after a role ends',scenario:'equipment shipment information exists but receiving confirmation is still missing',lane:'equipment custody evidence and follow-up',owner:'the equipment and security owner',signal:'missing custody confirmations and open access checks',decision:'charging a worker, declaring loss, or deciding a security response'}
];

export const august20BlogBatch:readonly August20BlogPost[] = topics.map((t,index)=>({slug:t.slug,title:t.title,excerpt:`A practical guide to ${t.question} in Philippines-based employment support.`,minutes:10,publishedDate:'2026-08-20',body:makeBody(t)}));
