type NewPost = { slug: string; title: string; excerpt: string; minutes: number; publishedDate: string; image: string; body: string[] };

const makeBody = (topic: string, decision: string, evidence: string, boundary: string, risk: string, handoff: string, measure: string) => [
  `August 21, 2026. ${topic} is easiest to manage when the recurring work is described before anyone is asked to move it into a queue. Start with the event that creates the task, the record that must be updated, the person who can decide an exception, and the evidence that proves the work is finished. For Philippines-based outsourced employment support, this description prevents a helpful coordinator from being treated as an unassigned employment decision-maker. The coordinator can prepare facts, organize a response, and show the open question; the employer keeps authority over policy, pay, eligibility, discipline, access, and other consequential calls.`,
  `Write the first version as a lane rather than a job-title promise. Name what arrives, where it arrives, how it is acknowledged, which source is authoritative, and when the next review occurs. ${decision} should be visible in the lane itself, because an item can be urgent without being approved. A practical role brief gives a Philippines-based specialist examples of ordinary work, incomplete work, and conflicting work. Those examples reveal whether the process is actually teachable or whether the business is relying on informal memory.`,
  `The intake record should be small enough to use every time. Capture a stable reference, received time, subject reference, requested outcome, source link, sensitivity level, current state, named owner, and next action. Do not paste a full employee history into a shared queue when two facts and a controlled link are enough. ${evidence} is more useful than a confident sentence because another reviewer can reconstruct what was checked, what was missing, and why the item moved.`,
  `Use states that describe the work: received, checking, waiting for source, waiting for owner, approved, implemented, and closed. Each state needs an entry rule and an exit rule. A reminder is not approval, an approval is not implementation, and implementation is not evidence until the record or system confirms it. This distinction is central to ${topic.toLowerCase()}. It keeps a remote support role focused on preparation while giving the employer a reliable point at which to review the decision.`,
  `Set the access boundary from the first task, not from a possible future expansion. A named account, least-privilege permission, multifactor authentication where available, and a review date are more useful than broad access granted for convenience. ${boundary} The owner of each permission should be explicit, as should the event that triggers removal. If a workflow grows, revise the role brief and access map together instead of solving uncertainty with administrator rights.`,
  `Build a work sample around a realistic request. Ask the specialist to identify the source, prepare the record, mark missing information, draft one neutral follow-up, and stop at the decision boundary. Review accuracy, privacy restraint, source discipline, writing clarity, and escalation judgment. A polished answer that invents a missing fact should fail the sample. A careful record that says waiting for owner can be the correct result in outsourced employment operations, because it protects the employee and the business from an unsupported conclusion.`,
  `The most useful checklist has a stop rule. ${risk} If the source conflicts, the requested effective date is absent, the person lacks authority, or the item could change money, access, eligibility, or employment status, pause the routine lane. Preserve the original request, list the sources checked, state the precise gap, and name the owner who must answer. Do not hide the pause by marking the item complete or by converting a message into a permanent record without confirmation.`,
  `Design the handoff so it can be answered quickly. ${handoff} A good handoff contains the request, the relevant source references, the current state, the proposed next action, and one decision question. It does not contain speculation about motive or an unrequested interpretation of policy. This format helps a manager review work across time zones and lets the Philippines-based specialist continue with other safe tasks while the consequential question remains with its authorized owner.`,
  `Review the lane at a fixed cadence. Sample ordinary items for completeness, unusual items for escalation quality, and closed items for proof of implementation. ${measure} Counts alone do not establish quality; they only show where to inspect. Track missing fields, returned items, source conflicts, waiting time, rework, and unresolved ownership. Then read representative examples. A smaller queue with transparent exceptions is safer and more useful than a larger queue whose completion count disguises unresolved decisions.`,
  `Keep corrections reusable. When a manager returns an item, record what changed, which source settled the question, and whether the written instruction needs an example. Do not rewrite the original record to make the first attempt look correct. A correction log turns individual feedback into a controlled improvement loop for Philippines-based employment support. It also gives a provider or internal manager a concrete basis for coaching without making unsupported claims about a person or a service result.`,
  `Plan for absence and continuity before the queue depends on one person. Name a backup reviewer, a second person who can grant or remove access, and the location of the current checklist. Keep open work, owner decisions, and pending sources visible. If a replacement or coverage change occurs, transfer the record with its history rather than recreating it from memory. The goal is continuity of accountable work, not a promise that every transition will be frictionless.`,
  `At the end of the first review cycle, compare the real queue with the written scope. Group repeated questions, permission requests, source disagreements, and items that reached the boundary unexpectedly. Expand the role only when the new task has an owner, examples, a quality check, appropriate access, and an escalation path. ${topic} should become more predictable through evidence and clear decisions, not through vague instructions to be faster or more proactive.`,
  `A manager can use this guide as a one-page operating conversation: what starts the task, what the specialist prepares, what the employer decides, what evidence closes the loop, and what happens when the facts do not agree. That conversation is especially important when work crosses a provider, a remote specialist, and an internal employment owner. Clear boundaries preserve speed without pretending that coordination is the same thing as authority.`,
  `The durable result is a record that another responsible person can understand without a private explanation. It shows the request, the source, the action taken, the owner decision, the effective date when one was actually supplied, and the proof of completion. That standard keeps ${topic.toLowerCase()} practical, reviewable, and appropriate for a Philippines-focused outsourced employment workflow. It also leaves room for qualified legal, tax, and employment advice where the facts require it, rather than implying that an operations checklist can replace professional judgment.`
];

const specs = [
  ['philippines-employment-intake-quality-gate','Philippines Employment Intake Quality Gate','Use a quality gate to separate complete employment requests from items that need facts or owner review.','the employment owner keeps the decision about whether a request may proceed','the gate is bypassed because a request arrived through a familiar channel','send a short summary with sources checked, missing facts, and one decision question','sample both accepted and rejected requests each week'],
  ['philippines-onboarding-owner-map','Philippines Onboarding Owner Map','Map onboarding tasks to responsible owners so documents, accounts, introductions, and approvals do not disappear between teams.','the employer confirms the start conditions and retains employment decisions','an onboarding task has several helpers but no accountable owner','show the task, current state, source record, owner, due point, and blocker','review overdue tasks by owner and reason, not just by count'],
  ['philippines-leave-calendar-exception-review','Philippines Leave Calendar Exception Review','Review leave-calendar exceptions without turning an administrative check into an eligibility decision.','the authorized manager confirms entitlement, approval, and any policy exception','a calendar entry conflicts with an approval record or current balance','preserve both records, describe the difference, and ask which source governs','sample exceptions for source quality and manager response time'],
  ['philippines-payroll-cutoff-evidence-pack','Philippines Payroll Cutoff Evidence Pack','Assemble payroll inputs with a traceable evidence pack while approvals and payment authority remain separate.','the payroll or employment owner approves the final inputs and payment action','a late change is accepted without a source, effective date, or approval','list each changed input, source, checker, owner decision, and unresolved item','reconcile returned inputs and late changes at every cutoff'],
  ['philippines-employee-record-retention-routine','Philippines Employee Record Retention Routine','Create a retention routine that keeps employee records findable without retaining unnecessary material.','the record owner decides retention, legal holds, and deletion under applicable policy','a convenient duplicate is retained without a purpose or review date','identify the source record, purpose, retention instruction, and responsible reviewer','inspect sampled folders for naming, access, duplicates, and review dates'],
  ['philippines-benefits-question-escalation','Philippines Benefits Question Escalation','Route benefits questions to the right owner while a support specialist prepares facts and follow-up.','the plan or employment owner answers eligibility and coverage questions','a general explanation is mistaken for a decision about a person','state the question, source plan language, personal facts supplied, and owner needed','review unanswered questions and repeated source gaps'],
  ['philippines-performance-review-cycle-tracker','Philippines Performance Review Cycle Tracker','Track review-cycle preparation without making ratings, feedback, or employment decisions.','the manager owns feedback, rating, goals, and any employment consequence','a coordinator turns a missing manager input into an inferred rating','show the cycle step, evidence received, manager action, and next date','sample completed cycles for evidence and owner confirmation'],
  ['philippines-offboarding-access-inventory','Philippines Offboarding Access Inventory','Use an access inventory to coordinate offboarding and preserve a clear trail of removal and handoff.','the authorized owner confirms the end event and access-removal priority','access is removed from one system while open work and shared credentials remain unresolved','link each account, owner, removal evidence, open work, and final confirmation','reconcile the inventory against actual systems and open tasks'],
  ['philippines-policy-change-brief','Philippines Policy Change Brief','Prepare a concise policy-change brief with version evidence, impact questions, and approval points.','the policy owner approves interpretation, effective date, and communication','an informal announcement is treated as the governing version','compare old and new sources, list affected workflows, and ask for approval','review changes for source version, audience, and rollout evidence'],
  ['philippines-recruiting-interview-evidence-log','Philippines Recruiting Interview Evidence Log','Keep recruiting interview evidence organized while selection judgment stays with the hiring owner.','the hiring owner decides progression, rejection, and offer terms','a coordinator converts an incomplete note into a candidate judgment','separate scheduling facts, submitted evidence, interviewer feedback, and next decision','sample logs for completeness, neutrality, and owner action'],
  ['philippines-remote-employee-absence-log','Philippines Remote Employee Absence Log','Maintain an absence log that records notifications and follow-up without deciding leave or discipline.','the employer confirms attendance status, leave treatment, and any response','a missed message is interpreted as an attendance conclusion','record notification time, source, follow-up, owner, and unresolved facts','review open absences by age, missing source, and named owner']
  ,['philippines-employee-data-change-approval','Philippines Employee Data Change Approval','Control employee-data changes with source checks, approval ownership, and evidence of the final record.','the record owner confirms which change is authorized and when it takes effect','a requested edit is applied before the source and approver are confirmed','show old value, requested value, source, approver, effective date, and completion proof','sample changes for source match, approval, and retained history']
];

export const august21BlogBatch: NewPost[] = specs.map(([slug,title,excerpt,decision,boundary,risk,handoff,measure], index) => ({
  slug, title, excerpt, minutes: 10 + (index % 3), publishedDate: '2026-08-21',
  image: `/blog-thumbnails/aug21-${slug.replace(/^philippines-/,'')}.png`,
  body: makeBody(title, decision, 'A source link and a brief evidence note', boundary, risk, handoff, measure),
}));

export const august21PromptReceipts = specs.map(([slug]) => ({ slug, prompt: `Distinct Gemini editorial hero for ${slug}; productivity-visual, Philippines-focused outsourced employment operations, no text, logos, watermark, or stock-photo look.` }));
