export type Oct5BlogDraft = {
  slug: string;
  title: string;
  excerpt: string;
  minutes: number;
  image: string;
  cta: string;
  sources: { name: string; url: string }[];
  body: string[];
  publishedDate?: '2026-10-06';
};

const privacySources = [
  { name: 'Philippine Supreme Court E-Library — Republic Act No. 10173', url: 'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html' },
  { name: 'Philippine Supreme Court E-Library — Republic Act No. 10173', url: 'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html' },
  { name: 'NIST — Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
  { name: 'NIST — Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
];

const laborSources = [
  { name: 'Philippine Supreme Court E-Library — Labor Code of the Philippines', url: 'https://lawphil.net/statutes/presdecs/pd1974/pd_442_1974.html' },
  { name: 'Philippine Supreme Court E-Library — Labor Code of the Philippines', url: 'https://lawphil.net/statutes/presdecs/pd1974/pd_442_1974.html' },
  { name: 'Philippine Supreme Court E-Library — Republic Act No. 10173', url: 'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html' },
  { name: 'NIST — Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
];

export const october5BlogDrafts: Oct5BlogDraft[] = [
  {
    slug: 'philippines-employment-support-scope-exclusion-map',
    title: 'Map What a Philippines Employment-Support Scope Excludes',
    excerpt: 'Make retained work, dependencies, and exception ownership visible before a provider statement of work is signed.',
    minutes: 8,
    image: '/blog-thumbnails/sop-template.svg',
    cta: '/services/workforce-reporting',
    sources: privacySources,
    body: [
      `A scope of work can list dozens of included activities and still leave the buyer uncertain about who handles the difficult moments. The missing information usually sits at the edges: a request arrives after cutoff, an employee record conflicts with its source, an approver is away, or a system rejects an otherwise approved update. An exclusion map makes those edges reviewable. It pairs every recurring service lane with the work the Philippines-based support team prepares, the decision another owner retains, and the evidence required before work can move. This is more useful than treating “out of scope” as a catch-all refusal after launch.`,
      `Begin with events, not department labels. “Payroll support” is too broad to assign safely. Separate new-hire inputs, recurring time records, approved allowances, one-time deductions, late changes, provider rejects, correction questions, release, and employee communication. Do the same for onboarding, leave, benefits, records, schedules, training, reporting, and offboarding. For each event, write the trigger, source, normal cutoff, destination, acceptance evidence, and accountable decision owner. The result reveals whether the proposed service covers a complete operating lane or only the visible administrative step in its middle.`,
      `Use four exclusion categories. A retained decision is something the client, employer, provider, or qualified adviser must decide, such as employment terms, leave approval, payroll treatment, access risk, or a legal interpretation. A dependency is an input the support team needs but does not control. A prohibited action is work the coordinator must not perform, such as sharing credentials or changing an approved source in place. An optional service is available only through an agreed process or commercial change. These categories lead to different responses; combining them under “excluded” creates delay and arguments.`,
      `Test the map with a concrete example. A manager sends an allowance instruction after the stated payroll-input cutoff. The support coordinator may timestamp the request, preserve the closed input version, check whether the named approval is present, and prepare a comparison for payroll. The coordinator should not insert the amount into a private copy, promise when it will be paid, or infer that the manager can approve every payroll field. The map should identify who decides treatment, what evidence that owner receives, which processing window may be affected, and who communicates an authorized outcome.`,
      `Record handoffs in both directions. Buyers often document what they send to a provider but not what the provider returns. If an onboarding document is defective, define the rejection evidence, permitted detail, recipient, response window, correction route, and resubmission identifier. If a benefits file is accepted, distinguish transport acceptance from confirmation that each approved record reached the intended state. If access removal is requested, define what post-action observation closes the task. A service lane without return evidence encourages teams to call transmission completion.`,
      `Add volume and timing assumptions beside every boundary. A process designed for ten predictable updates can fail when one hundred arrive before a holiday. State the operating timezone, daily and peak volume, planned cutoffs, required overlap, holiday route, and response expected from retained owners. Do not turn an assumption into a guarantee. Instead, specify the signal that triggers capacity review or reprioritization. A visible assumption allows both parties to change the design before queues grow; a hidden assumption appears later as blame.`,
      `Keep sensitive details out of the scope map. It needs data classes and approved systems, not real identity numbers, bank data, medical context, disciplinary notes, or employee messages. Link each lane to its controlled source and name the minimum access the coordinator requires. The Philippine Data Privacy Act is a primary reference for personal-information handling. The NIST Privacy and Cybersecurity Frameworks can help structure governance questions, but the organization’s authorized privacy, security, employment, and legal owners must apply requirements to the actual arrangement.`,
      `Review proposed automation against the exclusions. An intake rule may classify a request, check required fields, or notify an owner. It should not convert an ambiguous message into an employment instruction, approve a correction, or send sensitive content to a broad channel. Record the automation owner, inputs, output, fallback, permissions, monitoring, and manual stop. If the automation fails, the exclusion map should show who can contain the problem and which actions remain frozen until reliable evidence returns.`,
      `Use the map during provider evaluation. Ask each provider to walk one normal event, one exception, one missing approval, one system failure, and one urgent case from source through verification. Request sanitized examples of the intake record, decision handoff, rejected-item evidence, destination acknowledgment, and service measure. A policy or sales demonstration can support due diligence, but it does not prove that the proposed operating path is staffed, accessible, and understood. Compare the residual work left with your team as carefully as the included task list.`,
      `After launch, review exclusions using real case evidence. Count requests returned for missing inputs, time waiting for retained decisions, actions stopped for lack of authority, optional work requested repeatedly, unsafe workarounds, and cases reopened after false closure. The objective is not to pull every edge case into scope. It is to decide deliberately whether to clarify intake, train an owner, adjust access, change capacity, add a service, or retain the boundary. Version the map and preserve its effective date so historical cases remain understandable.`,
      `A strong exclusion map gives a buyer an operational answer to “what happens next?” It makes preparation useful without disguising who retains employment, payroll, privacy, security, finance, or legal authority. Outsourced Employment can help document recurring service lanes, evidence handoffs, and owner questions for a Philippines staffing conversation. Your organization and its qualified advisers keep the decisions assigned to them by law, policy, contract, and the actual employment arrangement.`,
    ],
  },
  {
    slug: 'philippines-payroll-calendar-change-communication',
    title: 'Communicate a Philippines Payroll Calendar Change Without Creating Two Cutoffs',
    excerpt: 'Version the calendar, identify affected work, and retire stale reminders when a payroll milestone changes.',
    minutes: 8,
    image: '/blog-thumbnails/payroll-cutoff-calendar.svg',
    cta: '/services/payroll-input-preparation',
    sources: laborSources,
    body: [
      `A payroll calendar change looks like a scheduling task, but its real risk is competing instructions. A provider email may move an input deadline while a manager reminder, shared sheet, recurring task, and written procedure still show the earlier date. People then submit against different versions, and the support team cannot tell whether an item was late. Treat the change as controlled operational information: preserve the received notice, confirm authority, identify every dependent milestone, publish one superseding version, and obtain evidence that the working destinations changed.`,
      `First distinguish the dates involved. The employee pay date, client funding date, provider file deadline, internal approval cutoff, coordinator preparation window, correction deadline, and communication date are not interchangeable. Record each timestamp with an explicit timezone. A deadline at the end of a Manila workday may fall on a different calendar date for a manager elsewhere. Do not shorten the chain into “payroll due Friday.” That phrase can mean several events and gives no one enough information to determine which work is affected.`,
      `Validate the source before editing calendars. Capture the notice, sender or system, receipt time, stated effective period, affected payroll population, reason if provided, and named contact for questions. Check it against the approved provider channel or contract owner. A forwarded screenshot without context is a lead, not necessarily an instruction. If authority or scope is unclear, preserve the current calendar, flag the conflict, and ask the payroll owner a narrow question rather than guessing which date is safer.`,
      `Build an impact list from the changed milestone. If the provider input deadline moves forward, internal manager approvals, time-record reconciliation, new-hire confirmation, approved variable inputs, leaver checks, funding review, and exception packaging may also need earlier dates. Some events should not move automatically. A change to input timing does not itself authorize different pay treatment, an earlier employment decision, or reduced review. Name the owner who decides each dependent change and record any step that remains on its existing schedule.`,
      `Create a versioned calendar record. It should show the payroll population, period, milestone name, old timestamp, new timestamp, timezone, source, approval, effective date, superseded version, change owner, and destinations to update. Keep the old version read-only for history instead of overwriting it. Historical cases need the calendar that applied when they were received. A version label in the document title is helpful, but the working system should also make the current status and effective period visible.`,
      `Update operational destinations as one controlled change set. These may include the payroll tracker, manager reminders, recurring tickets, intake form guidance, team calendar, provider handoff checklist, service dashboard, and escalation rules. Assign a person to each destination and capture completion evidence. Search for stale copies after the update. A polished announcement cannot compensate for an old recurring task that continues generating the superseded cutoff every month.`,
      `Communicate by audience. Managers need the input and approval deadlines they own, the effective period, the timezone, and the route for a late item. Coordinators need the full dependency chain, new workback dates, and stop rules. Payroll and finance owners need the controlled source, population, review effect, and unresolved exceptions. Employees should receive only an authorized message relevant to them; an internal calendar adjustment should not become an unsupported promise about payment timing or individual treatment.`,
      `Handle work already in flight. Freeze a population of open inputs at the moment the change is accepted. For each item, record whether it can meet the new cutoff, was already valid under the prior instruction, needs an owner decision, or should follow an approved transition rule. Do not silently relabel previously on-time submissions as late. If the owner grants a transition exception, identify its population and period so it does not become an undocumented standing practice.`,
      `Protect payroll information while coordinating the change. General reminders usually need a period, milestone, and link, not employee amounts, bank details, tax data, or private reasons for an adjustment. Keep restricted values in approved payroll or HR systems and use case tokens in broad trackers. The Philippine Data Privacy Act is a primary reference for personal-information handling. Labor and payroll owners, finance, privacy, legal advisers, and the authorized provider determine the rules that apply to the specific arrangement.`,
      `Verify adoption during the first affected cycle. Compare submitted items with the new calendar, identify which channel drove late or duplicate work, and inspect any exceptions individually. Useful measures include acknowledgments by owner group, stale reminders found, inputs submitted to the wrong version, time awaiting decisions, duplicate files, and corrections caused by timing confusion. Separate delays caused by the calendar rollout from unrelated input defects so the review produces a precise repair.`,
      `Prepare a specific late-input route before announcing the new calendar. The route should capture the original event date, submission time, approval state, affected field, current payroll version, approaching milestone, and employee-impact question without deciding the outcome. Name the payroll owner who can accept, defer, reject, or request more evidence and the coordinator who will observe the chosen destination. This prevents an earlier cutoff from driving private spreadsheets, duplicate provider emails, or informal promises when a legitimate item misses the revised window.`,
      `Close the change only after the destination state is observed. The approved calendar should be accessible, superseded versions clearly marked, automated reminders aligned, owners acknowledged, and transition cases resolved or assigned. Retain the evidence packet with the source notice and change record. Outsourced Employment can help maintain the calendar, coordinate acknowledgments, and package exceptions. Payroll, finance, employment, privacy, legal, and provider owners retain decisions about calculations, release, compliance, employee outcomes, and communications.`,
    ],
  },
  {
    slug: 'philippines-employee-support-inbox-privacy-triage',
    title: 'Triage a Philippines Employee-Support Inbox by Privacy Lane',
    excerpt: 'Route employee questions using observable content and minimum access without diagnosing or deciding the case.',
    minutes: 8,
    image: '/blog-thumbnails/hr-inbox-triage.svg',
    cta: '/services/employee-records-management',
    sources: privacySources,
    body: [
      `An employee-support inbox brings routine questions and highly sensitive material into the same queue. A request for a payslip, a leave question, a bank-detail change, a medical attachment, and a complaint may arrive with similar subject lines. Giving every coordinator access to every message is simple but difficult to justify. A privacy-lane triage design lets a Philippines-based support team recognize observable routing signals, limit unnecessary viewing, and move the message to an authorized owner without diagnosing the issue or deciding an employment outcome.`,
      `Define lanes around handling needs rather than guessed employee intent. Useful examples include general process guidance, record correction, payroll evidence, benefits administration, leave administration, access or security, workplace concern, medical or accommodation context, and misdirected material. Each lane needs a permitted viewer group, minimum fields, approved destination, response template, urgency signals, and escalation owner. Avoid labels such as “problem employee” or “invalid claim.” Triage records should describe the message and routing factually, not add character judgments.`,
      `Use a two-pass intake. The first pass views only what is required to identify obvious risk and the correct lane: receipt time, sender identity through the approved channel, subject, attachment presence, and a limited preview where permitted. The second pass occurs inside the restricted lane and only for staff assigned to that purpose. If the first reviewer sees medical, identity, banking, disciplinary, safety, or complaint content, the procedure should say when to stop reading, how to restrict the item, and whom to notify.`,
      `Do not ask employees to repeat sensitive details in a general inbox. An acknowledgment can confirm receipt, give a case token, explain that the message was routed, and point to an approved secure channel if more information is needed. It should not promise eligibility, payment, approval, confidentiality beyond the actual controls, or a resolution time that depends on another owner. If the message went to the wrong address, preserve the minimum audit event and follow the approved containment and deletion process instead of forwarding it widely.`,
      `Separate urgency from authority. A message can require rapid routing without allowing the coordinator to decide it. Define observable urgency signals such as an imminent payroll cutoff, suspected account compromise, a stated immediate safety concern, an approaching employment event, or a failed critical access step. The procedure should name the contact order and backup. The recipient must have subject authority and appropriate access; a fast acknowledgment by someone unable to act is not resolution.`,
      `Design the triage record to minimize copying. Store a case token, received timestamp and timezone, lane, restricted-content flag, current owner, source link, acknowledgment status, next review time, and final routing evidence. Keep the employee’s full message and attachments in the approved restricted system. General dashboards should not reproduce medical facts, bank details, identity documents, allegations, performance narratives, or private correspondence. If metrics require categories, test whether small groups could identify a person and aggregate where necessary.`,
      `The Philippine Data Privacy Act is a primary reference for accountable personal-information processing. Purpose, proportionality, transparency, security, accuracy, retention, and data-subject rights need application to the actual organization and provider arrangement by authorized privacy and legal owners. NIST privacy and cybersecurity guidance can help teams frame data flows, roles, and risk. It does not decide employment obligations, resolve an employee case, or substitute for local professional advice.`,
      `Train with fictional messages that contain ambiguous and mixed content. One message might request a payroll correction and attach an unrelated medical certificate. Another may appear to be a routine address update but include identity documents. Ask reviewers to identify the first stop signal, choose the narrow destination, draft a bounded acknowledgment, and explain what they deliberately did not copy. Score source discipline, minimum viewing, correct restriction, escalation timing, and respect for decision boundaries rather than speed alone.`,
      `Audit access and routing together. Review named accounts, group membership, shared mailbox delegation, forwarding rules, downloads, exports, retention, and leaver removal. Then sample complete lineages from receipt through acknowledgment, restricted transfer, owner acceptance, response, and closure. A ticket marked transferred is not enough if the destination never accepted it. A mailbox permission removed from the interface may still persist through a group or mobile session. Record the observed post-state and unresolved uncertainty.`,
      `Set retention and correction rules for the triage metadata itself. A wrong lane can be corrected without erasing who saw the message, when restriction began, or which destination first received it. Record the earlier classification, correction reason, authorized reviewer, new destination, and any containment action. Decide how long minimal routing events and full message content are retained in their respective systems, and suspend routine deletion only through an approved hold. A permanent general-inbox archive is not a substitute for a purpose-based records decision.`,
      `Measure the health of each lane without turning sensitive cases into performance theater. Useful measures include time to bounded acknowledgment, time to authorized owner, misroutes, overexposure events, messages returned for missing information, duplicate employee contacts, aged cases by owner, and closure without destination evidence. Publish denominators and exclusions. A longer time may reflect appropriate restriction or owner review; separate coordinator handling from waiting before drawing a conclusion about service quality.`,
      `A privacy-lane inbox gives coordinators a safe and useful job: recognize, restrict, route, document, and follow up. It keeps interpretation, employment decisions, payroll treatment, accommodations, investigations, security response, and employee communications with authorized owners. Outsourced Employment can help document the lanes, intake record, acknowledgments, and review cadence for a Philippines support role. The client, employer, provider, and qualified advisers retain their respective legal, privacy, security, HR, payroll, and management responsibilities.`,
    ],
  },
  {
    slug: 'philippines-manager-reassignment-employment-record-controls',
    title: 'Control Manager Reassignment Across Philippines Employment Records',
    excerpt: 'Move approvals, reports, queues, and access when an employee’s manager changes without rewriting history.',
    minutes: 8,
    image: '/blog-thumbnails/employee-directory.svg',
    cta: '/services/employee-records-management',
    sources: privacySources,
    body: [
      `A manager change affects more than an employee directory. The old manager may own leave approvals, time reminders, performance tasks, schedule decisions, onboarding follow-up, training reviews, employee-support cases, reports, folders, and distribution groups. Updating only the visible manager field can leave work routed to someone who no longer has responsibility or can remove access before open decisions are transferred. Treat reassignment as a versioned employment-operations event with an effective time, approved source, dependency inventory, receiving owner, and verification.`,
      `Start with the authoritative instruction. Record the employee or population token, current and receiving manager, approved effective date and timezone, source, decision owner, reason category if appropriate, confidentiality restriction, and systems expected to change. The coordination team should not infer a reporting change from an organization chart draft, meeting invitation, or informal message. If sources conflict, preserve them and ask the employment or HR owner which instruction controls. Do not edit history to make the new assignment appear to have always existed.`,
      `Inventory dependencies before the effective event. Look for pending leave and schedule requests, payroll questions, performance cycles, training approvals, probation or onboarding reviews, equipment custody, access sponsorship, open employee-support cases, recurring reports, workflow rules, shared files, calendar events, and escalation contacts. Classify each dependency as transfer, retain temporarily by approved exception, close before change, or outside scope. A system list alone is insufficient because important ownership can live in tasks, reports, and routines rather than a profile field.`,
      `Separate record preparation from the employment decision. A Philippines-based coordinator can assemble the inventory, compare approved sources, schedule updates, prepare notices, track acknowledgments, and verify visible states. Authorized HR, employment, business, privacy, security, payroll, and system owners decide whether the reassignment occurs, which cases transfer, what each manager may see, how performance information is handled, and what is communicated to the employee. Silence or a calendar change should never substitute for that authority.`,
      `Plan the cutover around the effective timestamp. Some destinations can be prepared in advance but should not become active early. Others may require advance access so the receiving manager can accept work. Record the approved sequence. For example, export a list of open approvals, obtain transfer decisions, stage workflow changes, activate the new routing at the effective time, confirm receipt, then remove permissions the former manager no longer needs. If the change crosses timezones, write the local date and zone beside every activation.`,
      `Handle open decisions individually. A leave request reviewed by the former manager may remain valid, require transfer, or need another owner under the organization’s policy. The coordinator should not cancel or reapprove it merely because the reporting field changed. Preserve the request, earlier actions, current state, decision owner, transfer evidence, and next review point. Apply the same discipline to performance notes, schedule exceptions, payroll approvals, and employee concerns, especially where the receiving manager should not automatically receive all historical context.`,
      `Minimize personal information during coordination. The reassignment tracker usually needs tokens, systems, ownership states, timestamps, and restricted links, not pay amounts, medical facts, complaint details, identity records, or complete performance narratives. The Philippine Data Privacy Act provides primary guidance for accountable personal-information handling. NIST frameworks can help structure access and privacy reviews. Qualified owners must determine purpose, disclosure, retention, employee notice, and access for the actual relationship.`,
      `Verify each destination rather than trusting a bulk update report. Observe the employee directory, approval workflow, queue routing, reporting hierarchy, relevant shared resources, manager dashboards, and escalation lists. Confirm that the receiving manager can perform the approved task and that the previous manager no longer has unnecessary access. Test inherited group permissions and automated subscriptions. A successful import proves that a job ran; it does not prove that every affected state is correct or that hidden access disappeared.`,
      `Plan for a manager who is unavailable at cutover. The approved backup must know which actions they may take, which records they may view, and when their temporary authority ends. Do not route every case to a senior leader merely because the new manager has not acknowledged it. Use consequence-based priorities: a time-sensitive payroll or access item may need immediate authorized coverage, while a routine report can wait with a named next check. Record each temporary assignment separately so it does not become invisible permanent access.`,
      `Use a bounded employee communication. State the approved effective date, practical contact changes, and where to send immediate questions. Do not expose private rationale, promise outcomes in open cases, or imply that every historical record transferred. Coordinate timing so the system state and message do not contradict each other. If the employee reports an error, open a linked correction event that preserves the original change evidence rather than overwriting the reassignment record without explanation.`,
      `Measure reassignment quality through consequences. Track dependencies found after cutoff, approvals routed to the former manager, receiving-owner acknowledgments, access retained beyond the approved window, cases reopened, employee contacts caused by conflicting instructions, and time to verify critical destinations. Review failures by dependency type. One missed recurring report may reveal a weak ownership inventory; repeated late access removal may require a different sequence rather than more reminders.`,
      `Close only when the receiving owner has accepted the transferred work, critical routes show the intended state, unnecessary access is removed or covered by a dated exception, and unresolved cases have named owners and review times. Retain the source, inventory, decisions, observations, and correction history. Outsourced Employment can help coordinate this evidence and follow-up for a Philippines support lane. The client and authorized employment, HR, privacy, security, payroll, legal, and system owners retain substantive decisions.`,
    ],
  },
];
