export type Sep14BlogPost={slug:string;title:string;excerpt:string;minutes:number;publishedDate:'2026-09-14';image:string;body:string[]};
type Topic=[string,string,string,string,string,string,string];
const topics:Topic[]=[
['philippines-employment-case-owner-absence-cover','Set Cover Before an Employment Case Owner Is Absent','Keep a case moving without giving an unbriefed colleague authority they do not have.','/blog-thumbnails/handoff-documentation.svg','the case reference, current stage, governing source, open question, due date, and safe next action','eligibility, pay, access, discipline, or policy','the owner returns, new evidence changes the question, or the covering person reaches the stated boundary'],
['philippines-onboarding-name-mismatch-hold','Handle a Name Mismatch During Onboarding','Pause the affected step while the identity owner reviews conflicting records.','/blog-thumbnails/onboarding-documents.svg','each observed name, its source, affected destination, and protected evidence reference','legal names, payroll identity, benefits identity, or account ownership','the authorised owner states the accepted value for each destination'],
['philippines-payroll-input-approval-expiry-check','Check Whether Payroll Input Approval Has Expired','Do not carry an old approval into a new pay period without checking its scope.','/blog-thumbnails/payroll-checks.svg','the approval reference, pay period, population, input version, effective date, and expiry condition','payroll treatment, approval validity, cutoff exceptions, or release','the payroll owner confirms the approval scope for the current run'],
['philippines-leave-calendar-partial-day-check','Reconcile Partial-Day Leave Across Calendars','Use explicit times and units so partial leave does not become a full-day absence.','/blog-thumbnails/leave-reconciliation.svg','the approved date, start and end times, named time zone, unit, and source reference','entitlement, rounding, payroll treatment, or exceptions','each required destination shows the accepted value or has an exception owner'],
['philippines-recruiting-candidate-withdrawal-record','Record a Candidate Withdrawal Without Rewriting History','Keep the candidate message, pipeline status, and follow-up boundary distinct.','/blog-thumbnails/candidate-follow-up.svg','the message identifier, received time, channel, candidate identifier, role, and pipeline stage','withdrawal reasons, future eligibility, retention, or hiring outcomes','the recruiting owner accepts the status and conflicting reminders are cleared'],
['philippines-benefits-provider-file-return-log','Log a Benefits Provider File Return','Turn a rejected file into a controlled correction instead of an email chase.','/blog-thumbnails/benefits-support.svg','the transmitted version, receipt, returned rows or codes, protected evidence link, and correction owner','eligibility, coverage, effective dates, contributions, or exceptions','the provider result has been reconciled row by row'],
['philippines-offboarding-forwarding-rule-review','Review Mail Forwarding Before Offboarding','Define the need, recipient, duration, and privacy boundary before forwarding starts.','/blog-thumbnails/offboarding-handoff.svg','the account, approved recipient, start and end times, excluded message classes, and approval','access, retention, disclosure, deletion, or legal exceptions','the temporary rule is verified and removed on its recorded expiry date'],
['philippines-training-prerequisite-exception-queue','Build a Queue for Training Prerequisite Exceptions','Keep missing prerequisites visible without allowing support staff to waive them.','/blog-thumbnails/training-attendance.svg','the course version, participant identifier, prerequisite, evidence reference, due date, and state','waivers, substitutions, deadline changes, scores, or consequences','the training owner records a decision and the learning system matches it'],
['philippines-employee-directory-role-change-check','Verify an Employee Directory Role Change','Keep directory labels aligned with the approved role record and access process.','/blog-thumbnails/employee-directory.svg','the approved role record, effective date, destinations, current values, and request owner','reporting lines, permissions, compensation, or employment status','every named destination is verified or assigned to an exception owner'],
['philippines-hr-inbox-restricted-attachment-routing','Route a Restricted Attachment From the HR Inbox','Move sensitive material to the approved system while keeping a minimal intake trail.','/blog-thumbnails/hr-inbox-triage.svg','the message identifier, received time, sender token, case category, and protected storage reference','access, retention, confidentiality treatment, response, or employment action','the protected location and next owner have both been verified'],
['philippines-workforce-report-filter-version-note','Add a Filter Version Note to a Workforce Report','Make a changed population filter visible before readers compare results.','/blog-thumbnails/reporting-calendar.svg','the filter version, effective date, included statuses, exclusions, period, and query reference','definitions, materiality, interpretation, disclosure, or restatement','the reporting owner accepts the definition and the published note identifies it'],
['philippines-employment-sla-pause-reason-log','Use a Pause Reason in Employment Service Tracking','Keep elapsed-time reports from treating every wait as active handling time.','/blog-thumbnails/queue-management.svg','the permitted pause reason, start event, owner, next check, restart event, and raw elapsed time','which pauses count, target thresholds, exceptions, or service outcomes','the restart event is recorded and another reviewer can reproduce the calculation'],
];
export const september14BlogBatch:Sep14BlogPost[]=topics.map(([slug,title,excerpt,image,fields,decisions,close])=>({slug,title,excerpt,image,minutes:8,publishedDate:'2026-09-14',body:[`Start with a case record containing ${fields}. Keep corrections as dated events instead of overwriting the earlier state.`,`Use explicit states such as received, incomplete, conflicting, ready for review, accepted, returned, and cannot determine. A status needs a source event, not an assumption based on silence or familiarity.`,`Coordination support can collect evidence, compare declared fields, maintain the queue, and route one precise question. The authorised owner decides ${decisions}.`,`Store private material in the approved restricted system and point to it from the operating record. Do not copy sensitive values into a shared tracker or public message.`,`Close the check only when ${close}. Record the source used, action taken, verification result, next owner, and date.`]}));
