export type Sep23BlogPost={slug:string;title:string;excerpt:string;minutes:number;publishedDate:'2026-09-23';image:string;sources:{name:string;url:string}[];body:string[]};
type Topic={slug:string;title:string;excerpt:string;image:string;work:string;inputs:string;owner:string;sample:string;metric:string;cta:string};

const sources=[
  {name:'Philippines National Privacy Commission — Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'Philippines Department of Labor and Employment — Labor Code',url:'https://blr.dole.gov.ph/2014/12/11/labor-code-of-the-philippines/'},
  {name:'CISA — Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication'},
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}
];

const topics:Topic[]=[
  {slug:'philippines-accounts-payable-support-role-scorecard',title:'How to Score a Philippines Accounts Payable Support Role',excerpt:'Define invoice preparation, exception handling, review evidence, and payment boundaries before hiring.',image:'/blog-thumbnails/payroll-checks.svg',work:'invoice intake, purchase-order matching, duplicate checks, supplier follow-up, and an exception queue',inputs:'supplier reference, invoice date, purchase order, receipt evidence, coding proposal, duplicate result, discrepancy reason, reviewer, and due date',owner:'A finance owner approves suppliers, accounting treatment, payments, bank changes, write-offs, and policy exceptions',sample:'Give the candidate a masked set with a clean invoice, a duplicate, a missing receipt, and a changed supplier account; ask for a proposed queue and escalation note',metric:'first-pass completeness, duplicates caught, unsupported coding proposals, exceptions routed on time, and reviewer corrections',cta:'/services/payroll-input-preparation'},
  {slug:'philippines-crm-cleanup-specialist-hiring-guide',title:'Hiring a Philippines CRM Cleanup Specialist: A Practical Guide',excerpt:'Turn CRM cleanup into a controlled role with source rules, reversible changes, and measurable review.',image:'/blog-thumbnails/employee-directory.svg',work:'duplicate research, required-field checks, approved normalization, stale-record flags, and change reporting',inputs:'record ID, object type, current value, proposed value, authoritative source, rule applied, confidence state, approver, and change time',owner:'Sales or data owners decide merges, deletions, ownership changes, lifecycle stages, consent, and schema rules',sample:'Provide masked contacts with one obvious formatting issue, one possible duplicate, and one source conflict; ask the candidate to separate safe corrections from decisions',metric:'accepted corrections, false merges avoided, unresolved source conflicts, rollback success, and sampled error rate',cta:'/services/employee-records-management'},
  {slug:'philippines-executive-calendar-support-work-sample',title:'A Work Sample for Philippines Executive Calendar Support',excerpt:'Test scheduling judgment without giving a candidate live inbox access or authority to make commitments.',image:'/blog-thumbnails/meeting-notes.svg',work:'meeting-request intake, timezone checks, option preparation, conflict flags, briefing reminders, and approved calendar updates',inputs:'requester, purpose, attendees, duration, timezone, deadline, priority rule, dependencies, confidentiality class, and approval state',owner:'The executive retains priority, attendance, disclosure, travel, spending, and relationship decisions',sample:'Use a fictional week containing a double booking, a Manila-to-New York conversion, a confidential hold, and an incomplete request; ask for options and questions',metric:'timezone accuracy, conflicts surfaced, required context preserved, unauthorized commitments avoided, and revision count',cta:'/services/schedule-administration'},
  {slug:'philippines-customer-support-qa-specialist-scorecard',title:'Build a Scorecard for a Philippines Customer Support QA Specialist',excerpt:'Measure review consistency, evidence, and coaching inputs while policy decisions stay with support leaders.',image:'/blog-thumbnails/quality-scorecard.svg',work:'ticket sampling, checklist scoring, defect classification, evidence capture, calibration preparation, and trend summaries',inputs:'ticket ID, channel, policy version, sample reason, observable criterion, result, evidence pointer, defect class, reviewer, and appeal status',owner:'Support leaders define policy, waive defects, handle personnel decisions, approve remedies, and change customer promises',sample:'Ask the candidate to score five sanitized tickets, including an ambiguous policy case, then explain what needs calibration rather than forcing agreement',metric:'inter-reviewer agreement, evidence-backed findings, overturned scores, sampling coverage, and recurring process defects',cta:'/services/training-coordination'},
  {slug:'philippines-ecommerce-catalog-assistant-hiring-brief',title:'Write a Hiring Brief for a Philippines E-commerce Catalog Assistant',excerpt:'Scope catalog updates around approved product facts, image checks, launch gates, and exception ownership.',image:'/blog-thumbnails/daily-operations-summary.svg',work:'product-data intake, approved field entry, image and link checks, variant comparison, missing-asset follow-up, and prelaunch reports',inputs:'SKU, approved product source, title, description version, attributes, variants, media rights, price source, channel, publish state, and reviewer',owner:'Merchandising owners decide claims, pricing, promotions, substitutions, inventory promises, and final publication',sample:'Supply three fictional SKUs with a missing image, conflicting dimensions, and an unapproved price; ask for a draft, exception list, and release recommendation',metric:'fields accepted on first review, source conflicts found, broken assets, unauthorized live changes, and correction time',cta:'/services'},
  {slug:'philippines-recruiting-coordinator-capacity-plan',title:'Plan Capacity for a Philippines Recruiting Coordinator',excerpt:'Estimate workload from actual requisitions, interviews, candidate contacts, and manager dependencies.',image:'/blog-thumbnails/capacity-planning.svg',work:'requisition intake, candidate scheduling, status follow-up, interview logistics, document routing, and aging reports',inputs:'open roles, stage counts, expected interview volume, response windows, panel availability, recurring reports, peak events, and approval delays',owner:'Recruiting leaders decide candidate outcomes, compensation, offers, exceptions, hiring priorities, and assessment standards',sample:'Give the candidate a fictional week with several roles, reschedules, and a missing interviewer; ask for a prioritized plan and capacity risks',metric:'requests handled within the stated window, scheduling rework, stalled stages, missing acknowledgments, and hours waiting on owners',cta:'/services/candidate-sourcing-coordination'},
  {slug:'philippines-bookkeeping-assistant-first-30-days',title:'The First 30 Days for a Philippines Bookkeeping Assistant',excerpt:'Sequence access, examples, reconciliation practice, review, and expanded responsibility without moving financial authority.',image:'/blog-thumbnails/first-30-days.svg',work:'receipt collection, transaction-coding proposals, reconciliation preparation, missing-document follow-up, and close checklists',inputs:'approved chart guidance, source statements, receipt locations, period, reconciliation template, cutoff, reviewer, and exception route',owner:'A qualified finance owner approves entries, reconciliations, tax positions, payments, access changes, and unusual transactions',sample:'Begin with a closed historical period and masked records, require a traceable reconciliation, then compare every proposed treatment with the owner-reviewed result',metric:'supported proposals, unreconciled differences, missing documents resolved, review adjustments, and close tasks completed on time',cta:'/services'},
  {slug:'philippines-property-management-admin-role-design',title:'Design a Philippines Property Management Admin Role',excerpt:'Separate repeatable tenant and vendor coordination from leasing, money, safety, and legal decisions.',image:'/blog-thumbnails/queue-management.svg',work:'request intake, maintenance scheduling, approved notice preparation, vendor-status follow-up, document filing, and open-item reporting',inputs:'property and request IDs, requester channel, received time, category, urgency evidence, approved vendor route, access instructions, status, and owner',owner:'Property managers retain leasing, screening, rent, refunds, safety response, legal notices, vendor selection, and emergency decisions',sample:'Use fictional requests covering routine maintenance, a possible emergency, a payment question, and a privacy-sensitive complaint; ask for routing and draft updates',metric:'complete intake, urgent cases escalated, missed appointments, unauthorized promises, aging requests, and owner response time',cta:'/services'},
  {slug:'philippines-marketing-operations-assistant-work-sample',title:'A Work Sample for a Philippines Marketing Operations Assistant',excerpt:'Test campaign setup and QA with a sandbox, approved copy, source fields, and a clear release gate.',image:'/blog-thumbnails/process-change-approval.svg',work:'brief intake, campaign assembly, link and field checks, audience-file validation, approval tracking, and results-table preparation',inputs:'campaign ID, approved copy, asset version, destination URLs, audience source, exclusions, sender, schedule, consent rule, approver, and release status',owner:'Marketing owners decide claims, audiences, offers, spend, consent interpretation, brand exceptions, and launch',sample:'Provide a sandbox campaign with one stale asset, a broken tagged link, a suppressed contact, and no final approval; ask for a QA report rather than a send',metric:'defects found before release, false-ready campaigns, source fields preserved, approval gaps, and post-launch corrections',cta:'/services'},
  {slug:'philippines-procurement-coordinator-handoff-map',title:'Map the Handoffs for a Philippines Procurement Coordinator',excerpt:'Connect approved requests, quotes, purchase orders, receipt evidence, and invoice status without transferring buying authority.',image:'/blog-thumbnails/handoff-documentation.svg',work:'request completeness checks, quote organization, approved-order tracking, delivery follow-up, receipt matching, and exception summaries',inputs:'request ID, specification owner, budget reference, approved suppliers, quote versions, buyer decision, order number, delivery evidence, receipt status, and invoice link',owner:'Budget and procurement owners select suppliers, approve purchases, negotiate terms, accept substitutions, and release payment',sample:'Ask the candidate to map a fictional request with competing quote versions, a partial delivery, and an invoice that precedes receipt confirmation',metric:'requests ready for buyer review, version conflicts, unapproved substitutions, unmatched receipts, aged orders, and handoff rework',cta:'/services'},
  {slug:'philippines-project-coordinator-weekly-report-template',title:'Create a Weekly Report for a Philippines Project Coordinator',excerpt:'Report milestones, decisions, dependencies, and risks without turning status preparation into project authority.',image:'/blog-thumbnails/reporting-calendar.svg',work:'status collection, milestone reconciliation, dependency tracking, meeting-action follow-up, decision logging, and weekly report preparation',inputs:'workstream, owner, baseline date, current forecast, evidence link, blocker, decision needed, dependency, next action, and update time',owner:'Project sponsors and managers approve scope, priority, budget, deadlines, acceptance, and tradeoffs',sample:'Provide inconsistent fictional updates from three workstreams and ask for one report that preserves uncertainty, identifies decisions, and avoids invented percentages',metric:'updates received by cutoff, unsupported status claims, overdue decisions, dependency misses, forecast changes explained, and actions closed',cta:'/services'},
  {slug:'philippines-data-entry-specialist-quality-plan',title:'Build a Quality Plan for a Philippines Data Entry Specialist',excerpt:'Define source-of-truth rules, field validation, sampling, correction, and access before production entry begins.',image:'/blog-thumbnails/review-evidence.svg',work:'structured field entry, written normalization, validation checks, duplicate flags, batch control totals, and correction reports',inputs:'batch ID, source location, record identifier, field rule, original value, entered value, validation result, exception code, reviewer, and correction history',owner:'The data owner decides source conflicts, schema changes, deletion, retention, exports, and exceptions to validation rules',sample:'Use masked records containing legibility problems, duplicated identifiers, a valid blank, and a cross-source conflict; ask for entries plus an exception file',metric:'field error rate, critical errors, duplicate detection, exceptions incorrectly guessed, control-total differences, and correction recurrence',cta:'/services/employee-records-management'}
];

const body=(t:Topic)=>[
  `A useful ${t.title.toLowerCase()} starts with the work, not a generic job title. The initial lane is ${t.work}. Write down the expected volume, cutoff times, systems, examples, and review points before comparing candidates or providers. This makes the role easier to price, screen, launch, and manage. It also prevents a growing list of unrelated chores from becoming one impossible position. The goal is a bounded service lane with visible outputs, not a promise that one remote hire will absorb every task the business has not documented.`,
  `Map the inputs before assigning responsibility. The operating record should include ${t.inputs}. Each field needs an authoritative source and a reason it matters. A copied spreadsheet can support coordination, but it should not silently replace the approved business system. Where two sources disagree, preserve both references, label the conflict, and send one precise question to the person who owns the decision. A coordinator adds value by making uncertainty easy to review, not by hiding it behind a completed status.`,
  `Keep authority explicit. ${t.owner}. The Philippines-based specialist can prepare, compare, organize, draft, and report within written instructions. They should stop when a request changes policy, creates a financial or employment commitment, requires access they do not have, or depends on sensitive facts outside the approved record. Put these stop conditions in the hiring brief and reinforce them with real examples. Good boundaries protect the employee as well as the company because the person is not pressured to improvise decisions they were never authorized to make.`,
  `Use a realistic work sample before granting production access. ${t.sample}. Score observable behavior: whether the candidate follows the source rule, keeps versions distinct, identifies missing evidence, protects restricted data, and writes an escalation that an owner can answer. Do not reward confident guessing. A strong submission may leave an item unresolved when the available evidence does not support a safe action. Tell the candidate what tools and time are allowed, use fictional or properly masked data, and pay for substantial trial work when appropriate.`,
  `Design access from the task map. Start with named accounts, multifactor authentication, and only the records and actions needed for the first work lane. CISA recommends MFA as a protective control, while the NIST Cybersecurity Framework provides a shared structure for discussing governance, protection, detection, response, and recovery. These references are useful starting points, not proof that a particular setup is secure. Record who grants access, when it will be reviewed, how exceptions are approved, and how access is removed when duties or personnel change.`,
  `Privacy needs an operating rule, not a broad instruction to be careful. The Philippine Data Privacy Act provides important context for handling personal information. Translate the organization’s approved requirements into the role: which system holds the record, which fields belong in a coordination view, who may receive a link, how long working copies remain, and what happens when information arrives through the wrong channel. Avoid repeating identity numbers, financial details, health information, credentials, or private employee context in chat, task titles, screenshots, or general reporting. Route legal interpretations to qualified advisers.`,
  `Launch in stages. During the first week, use a small historical or low-risk batch and review every output. In the second stage, allow a narrow live queue with a daily correction window and a backup reviewer. Expand only after the acceptance rule is stable and the specialist can explain the escalation path in their own words. If volume grows, change one variable at a time: more records, a second task type, or a longer review interval. Increasing volume, scope, and permissions together makes it difficult to identify why quality changed.`,
  `Create a short standard operating procedure around the actual screen rather than an abstract flowchart. Show where work arrives, how the source is verified, which checks are required, how status is recorded, and what evidence proves completion. Include one ordinary example, one exception, and one returned item. Version the procedure and name its owner. When instructions change, state the effective date and identify the superseded version. A silent edit can leave two people following different rules while both believe they are using the current process.`,
  `Measure ${t.metric}. Pair the numbers with reviewed examples. A falling exception count can indicate improvement, or it can mean the specialist has stopped recording difficult cases. Separate active handling time from time waiting for an owner, customer, supplier, or unavailable system. Review trends at a consistent cadence and correct the process before turning every variance into an individual performance judgment. The scorecard should help a manager decide whether scope, instructions, access, review capacity, or training needs to change.`,
  `Plan continuity before the first absence or departure. Give the backup person access only to the same bounded lane, keep open work in a shared approved queue, and make every item’s next action visible. The handoff should state what is complete, what is waiting, which source governs, and who owns the next decision. Never transfer a shared password or export a broad dataset simply because it is faster. Test the backup process with one low-risk item and verify that access removal does not break an automation, ownership link, or reporting schedule.`,
  `Close work only when the required fields are present, the source and action are traceable, exceptions have owners, and the result appears in every required destination. A status such as sent or updated is not enough when another system, reviewer, or recipient must acknowledge the result. Keep corrections linked to the original item rather than deleting history. Apply the organization’s approved retention schedule to working evidence. Storage cost is not a justification for keeping personal or commercially sensitive information indefinitely.`,
  `Use the related service page at ${t.cta} to connect this role design to Outsourced Employment’s real conversion path. Bring a recent, non-sensitive sample of the queue, expected weekly volume, required schedule overlap, current tools, and the name of the person who will review early outputs. Ask a provider to explain the employment setup, management support, security controls, replacement terms, and what your own team must still own. This article offers general operational information and does not replace legal, tax, accounting, security, or employment advice for your circumstances.`
];

export const september23BlogBatch:Sep23BlogPost[]=topics.map(topic=>({...topic,minutes:10,publishedDate:'2026-09-23',sources,body:body(topic)}));
