type ResearchEntry = { slug: string; title: string; excerpt: string; publishedDate: '2026-08-17'; body: string[] };

const sources = {
  ilo: 'International Labour Organization, Working conditions and labour standards: https://www.ilo.org/topics/working-conditions',
  nist: 'NIST, Cybersecurity Framework 2.0: https://www.nist.gov/cyberframework',
  cisa: 'CISA, Secure Our World: Use strong passwords: https://www.cisa.gov/secure-our-world/use-strong-passwords',
  ftc: 'FTC, Protecting personal information: https://www.ftc.gov/business-guidance/privacy-security',
  world: 'World Bank, World Development Indicators for the Philippines: https://data.worldbank.org/country/PH',
  oecd: 'OECD, Digital economy policy: https://www.oecd.org/digital/',
};

function body(question: string, finding: string, method: string, specifics: string[], limits: string, refs: string[]): string[] {
  return [
    `Research question: ${question}`,
    `Executive finding: ${finding} This is a bounded finding about role design for Philippines-based employment administration, not a promise about every worker, provider, employer, or result. The useful test is whether a named owner can inspect the record and retain the decision the support role is not authorized to make.`,
    'Evidence scope: this study uses public material from the International Labour Organization, NIST, the FTC, the OECD, and the World Bank as context for work conditions, information protection, and digital operations. These sources do not prove a company-specific performance claim, certify a provider, or decide an employment obligation. Country indicators describe a population or period; they are not a capability score for an individual.',
    `Method: treat ${method} as a case-evidence problem. Review 20 sanitized cases from two ordinary work weeks and include routine records plus duplicates, stale information, missing approvals, conflicting instructions, and a request that could affect pay, employment status, privacy, security, or a customer commitment. For every case, record the source, period, permitted transformation, output, uncertainty, reviewer, and next decision owner.`,
    'A source of truth must be named before a queue is measured. A coordinator can collect records from approved systems, preserve links or identifiers, normalize fields whose meaning is already defined, and show discrepancies. They should not decide that the newest-looking or most convenient value wins. The owner needs to see the conflict and its provenance before approving a change.',
    'A useful output is more precise than “completed.” It names the case, date checked, source records consulted, fields changed or left unchanged, open question, and responsible next action. The output may be a review packet, a structured queue note, or a comparison table. Its format matters less than reproducibility by a reviewer who was not present when the work was prepared.',
    'Restraint is an operational control. A missing source, conflicting instruction, sensitive record, urgent deadline, and exception request should not share one generic status. The coordinator can pause, preserve the evidence, minimize the copy, and route the issue. The owner decides whether another source is required, the work can continue, or the request is outside the approved lane.',
    ...specifics,
    `Analytical test: for ${method}, separate the administrative observation from the employment conclusion. The observation is something a reviewer can locate in a record, such as a missing approval, a conflicting date, or an unanswered request. The conclusion may require authority that the support role does not hold. This separation matters in outsourced employment because a well-organized record can otherwise make an unverified assumption look official. The case review should therefore ask two questions in sequence: what does the evidence establish, and what decision is still reserved for the employer or designated owner?`,
    'The evidence unit should be the case, not the number of messages or fields touched. One employee request may produce several messages, while one change may affect several systems. Count the case once, preserve its supporting records, and note each output that was prepared. This prevents activity volume from becoming a misleading proxy for useful work. It also gives the manager a defensible way to sample ordinary cases and exceptions without rewarding unnecessary copying or repeated status updates.',
    'A comparison needs a stable baseline. If the lane is being assessed across two weeks, define the work period before reviewing the records and keep the inclusion rule unchanged. Do not compare a quiet week of routine requests with a week containing a policy change, system outage, or unusual hiring event as though they were equivalent. Describe the case mix, excluded cases, and missing evidence. A small, transparent sample is more informative than a larger count whose composition changed without notice.',
    `For a Philippines-based employment administration role, the local context belongs in the question being examined, not in an unsupported assumption about a worker. Ask whether the role brief identifies the systems, hours of overlap, language or documentation needs, and manager decisions that actually shape the work. Public country indicators can describe broad conditions, but they cannot establish an individual's skill, availability, judgment, or suitability. The operational evidence must come from the defined work and its review standard.`,
    'Source quality is part of the finding. A primary policy, system record, signed approval, or dated instruction should be distinguished from a summary, recollection, copied message, or unverified spreadsheet. Where sources disagree, preserve both versions and explain which question each can answer. Choosing the most convenient source without documenting the choice introduces a hidden rule that will be difficult for a new manager or reviewer to detect.',
    'The role boundary should be tested with deliberately difficult cases. Include a duplicate record, a late request, an ambiguous instruction, a sensitive field, and a case whose deadline is close. These cases reveal whether the lane has a real escalation path or merely sounds controlled when work is straightforward. The test is not whether the coordinator solves every exception; it is whether they identify the exception early, preserve the relevant evidence, and send it to the correct decision owner.',
    'Interpretation should distinguish a control from an outcome. A named reviewer, limited access, and an exception log are controls that can be inspected. They do not prove that every record is correct, that a worker is compliant, or that an employment decision is lawful. Report what was observed, what was inferred, and what remains unknown. This discipline is especially important when research is used to compare an internal role with outsourced employment administration.',
    `A practical decision rule for ${method} is to expand only when the evidence shows repeatability across the stated case period and the boundary remains understandable to the owner. If the sample depends on one unusually experienced person, one undocumented system shortcut, or one manager's memory, the apparent result is fragile. Preserve the dependency as a limitation and resolve it before treating the lane as ready for broader delegation.`,
    'The manager should receive findings in a form that supports a decision, not a performance story. State the sample, the observed pattern, the counterexamples, the unresolved risks, and the action that requires authorization. Avoid adjectives such as seamless, proven, or compliant unless a defined measurement and accountable authority support them. Clear uncertainty is not a weakness in the research; it is information about what the operating model still needs.',
    'A pilot should disclose its denominator and period. Count ordinary completions separately from corrections, escalations, missing-source cases, and unauthorized actions prevented. A high completion rate can be misleading if hard cases were silently excluded. Review the case mix before comparing weeks, and keep the definition stable when the result is reported.',
    'Distributed work adds timing questions. Record the source timestamp, the relevant work period, the time zone used for a comparison, and the owner’s due date. A local schedule can coordinate handoffs, but it does not establish an employment term, availability promise, overtime conclusion, or service-level commitment by itself.',
    'Access should follow the smallest useful packet. Use named accounts, narrow permissions, masked training examples, approved storage, and a review date for temporary access. The FTC and NIST support general protection principles; the employer must still decide which personal records are necessary, who may see them, and how long they are retained.',
    'Quality has two dimensions: correctness and authorization. Correctness asks whether the record agrees with its approved source and period. Authorization asks whether the role stopped when evidence or authority ended. Coaching should show the source, the mistaken inference, and the permitted next step. A polished unauthorized answer is not a quality success.',
    'Escalation should identify the kind of risk. A factual mismatch needs correction; a privacy concern needs a restricted route; an employment or policy question belongs with its responsible owner; and a suspected security event may require the organization’s incident process. A single “needs review” label hides urgency and encourages improvisation.',
    'Definitions must survive handoff. Keep proposed, approved, reported, effective, and corrected values distinct when they answer different questions. When a field definition changes, record the effective date and show the break in the series. A support role can maintain that evidence; the manager decides whether a measure supports an operational conclusion.',
    'Scope should expand one case class at a time. Add an adjacent task only after the lane has a stable source, reviewer, access owner, acceptance rule, and exception record. If exceptions grow faster than routine cases, narrow the lane or repair the upstream rule before increasing volume. This gives a Philippines-based specialist a fair standard and gives the owner a visible control point.',
    `Topic analysis: ${method} is valuable when it makes the owner’s decision easier without disguising a recommendation as a completed administrative record. ${specifics[0]} ${specifics[1]}`,
    'A review rubric should score evidence, not confidence or personality. Check source linkage, current period, allowed transformation, visible exception, authorized recipient, and explicit next owner. Use the same rubric for ordinary and difficult cases so speed does not become a hidden replacement for accuracy.',
    'Keep a change record for the lane. When a field, permission, template, owner, or exception rule changes, note the reason, effective date, approver, and affected cases. That history distinguishes a controlled improvement from a quiet expansion of authority and lets a new reviewer interpret older records without rewriting them.',
    `Limitations: ${limits} This article does not assess a particular contract, provider, employee, employer, or jurisdiction. Local rules, sector obligations, data sensitivity, customer expectations, and internal policies may change the correct boundary.`,
    'Conclusion: the strongest outsourced-employment support lane is specific enough to perform and narrow enough to inspect. Preserve the source, expose uncertainty, minimize access, and keep approval with the named owner. Those conditions make delegation more reliable without pretending that administration replaces judgment.',
    'Sources:', ...refs,
  ];
}

export const august17ResearchBatch: ResearchEntry[] = [
  { slug: 'philippines-role-brief-calibration-research', title: 'Philippines Role Brief Calibration: Evidence Before a Staffing Request', excerpt: 'Research how owners can calibrate a Philippines-based employment administration role from real work evidence without turning a task list into an unsupported hiring promise.', publishedDate: '2026-08-17', body: body('What evidence makes a Philippines staffing role brief specific enough for review before a hiring request is made?', 'role-brief calibration is strongest when recurring work, decision boundaries, tools, review evidence, and exceptions are separated before a staffing model is selected.', 'role-brief calibration', ['A task name such as “handle HR” hides different units of work. Record the case type, input, expected output, frequency, and decision that remains with the owner. This lets a manager compare a real lane with a broad title.', 'A brief should distinguish capability evidence from an aspiration. A prior example, a de-identified work sample, and a defined review standard are evidence; a country stereotype or a generic productivity claim is not.'], 'A role brief cannot establish worker classification, legal compliance, capacity, or suitability for a particular person or provider.', [sources.ilo, sources.world, sources.ftc]) },
  { slug: 'philippines-manager-handoff-records-research', title: 'Philippines Manager Handoff Records: Continuity Without Decision Drift', excerpt: 'Examine handoff evidence for Philippines-based staff while managers retain approval over open work, exceptions, and employment decisions.', publishedDate: '2026-08-17', body: body('Which handoff records preserve continuity when a Philippines-based specialist changes queue, manager, or work period?', 'a handoff is reliable when it preserves source, status, owner, deadline, and unresolved decision rather than compressing a case into an optimistic summary.', 'manager handoff records', ['“Pending” needs an owner and a date. A coordinator can identify the last confirmed event and list the next question, but should not mark a case resolved because the recipient has not yet replied.', 'Handoffs should preserve the distinction between an approved instruction and a suggestion. That distinction prevents a new manager from mistaking an old draft, informal message, or copied status for current authority.'], 'Continuity design varies with systems, confidentiality, work arrangements, and the employer’s policies; no particular handoff is validated here.', [sources.ilo, sources.nist, sources.ftc]) },
  { slug: 'philippines-employment-policy-question-routing-research', title: 'Philippines Employment Policy Question Routing: Evidence Before an Answer', excerpt: 'Study how a support role can classify employment-policy questions and preserve source context without giving unauthorized legal or HR advice.', publishedDate: '2026-08-17', body: body('How can Philippines employment administration route policy questions without turning a record coordinator into a policy authority?', 'question routing improves reliability when it preserves the exact question, relevant record, applicable policy version, and responsible owner instead of producing a confident answer from incomplete context.', 'employment-policy question routing', ['A policy question often contains several questions: what the record says, which policy version applies, and who may decide an exception. Keep those layers separate so a coordinator can answer a factual retrieval request while routing interpretation.', 'A copied policy paragraph is not a case decision. The coordinator can link the approved source and identify missing facts; HR or the designated owner determines how the policy applies to the person and circumstances.'], 'Employment policy and legal duties depend on facts, jurisdiction, and responsible professional review; this research is not legal or HR advice.', [sources.ilo, sources.ftc, sources.nist]) },
  { slug: 'philippines-workforce-change-records-research', title: 'Philippines Workforce Change Records: Traceability Before Employee Updates', excerpt: 'Assess how change-record administration can show who requested and approved a workforce update while owners retain authority over employment records.', publishedDate: '2026-08-17', body: body('What evidence should a Philippines-based coordinator preserve before a workforce change is entered into an employee system?', 'change administration is reviewable when request, source, approval, effective date, and resulting record are linked without allowing a support role to infer or approve the change.', 'workforce change records', ['Effective date, request date, and entry date answer different questions. Preserve each rather than overwriting the record with one convenient date, especially around transfers, leave, or payroll cutoffs.', 'A manager’s message may request an update but not prove that HR approved its employment effect. The coordinator can prepare the change packet and flag missing approval; the responsible owner decides whether the system entry is authorized.'], 'System design, employment records, payroll treatment, and applicable rules vary by employer and jurisdiction.', [sources.ilo, sources.nist, sources.ftc]) },
  { slug: 'philippines-employee-query-triage-research', title: 'Philippines Employee Query Triage: Evidence Before a Response', excerpt: 'Research a narrow employee-query lane that improves routing and response evidence while HR owners retain policy and personal-data authority.', publishedDate: '2026-08-17', body: body('Which evidence lets a Philippines-based employee-query coordinator route a request accurately without promising an outcome?', 'query triage adds value by identifying the request, checking approved references, protecting personal information, and routing the unanswered decision to its owner.', 'employee query triage', ['A request for a record is different from a request to change a record or interpret a policy. Use separate categories so a retrieval response does not accidentally become an approval.', 'The safest draft names what is known and what remains open. Avoid filling an unanswered question with customary practice, especially when pay, benefits, leave, discipline, or confidential data may be involved.'], 'Employee communications may involve confidential records, accommodations, disputes, or jurisdiction-specific duties beyond this general role-design study.', [sources.ilo, sources.ftc, sources.nist]) },
  { slug: 'philippines-employment-document-expiry-research', title: 'Philippines Employment Document Expiry: Evidence Before a Renewal Request', excerpt: 'Analyze expiry tracking for employment records and credentials without deciding renewal eligibility or employment status.', publishedDate: '2026-08-17', body: body('How can expiry tracking for Philippines employment documents surface timely action without creating an unauthorized renewal decision?', 'expiry administration is dependable when it records document identity, source date, effective period, owner, and notice status while the owner decides renewal, replacement, or consequence.', 'employment document expiry tracking', ['A reminder date is not an expiry date. Preserve the document’s stated period, the date it was checked, and the policy for advance notice so a coordinator does not turn a calendar alert into a conclusion.', 'An expired document does not automatically prove that a person is ineligible or that employment must stop. Route the evidence and urgency; the responsible owner decides what action applies.'], 'Document validity, licensing, employment consequences, and renewal rules depend on the record and jurisdiction; this is not a compliance determination.', [sources.ilo, sources.ftc, sources.nist]) },
  { slug: 'philippines-remote-work-location-records-research', title: 'Philippines Remote Work Location Records: Facts Before Coordination Decisions', excerpt: 'Study location-record coordination for Philippines-based staff while owners retain authority over work arrangements, security, and employment implications.', publishedDate: '2026-08-17', body: body('What can a remote-work location coordinator verify before an owner acts on a Philippines-based worker’s location record?', 'location support should preserve the reported place, source, period, time zone, and uncertainty without treating a single record as proof of a legal, tax, security, or employment conclusion.', 'remote-work location records', ['A location field can be stale, approximate, or collected for a different purpose. Record when and why it was obtained, minimize precision where it is unnecessary, and route a discrepancy rather than attempting to investigate a person informally.', 'A time-zone conversion supports coordination but does not establish the worker’s legal location or contract terms. Keep scheduling facts distinct from decisions about employment, access, tax, or safety.'], 'Location, privacy, tax, security, and employment effects require employer-specific review and may involve rules outside this article’s scope.', [sources.ilo, sources.ftc, sources.oecd]) },
  { slug: 'philippines-employee-access-request-research', title: 'Philippines Employee Access Requests: Evidence Before Permission Changes', excerpt: 'Examine access-request evidence for Philippines-based employment teams while system owners retain permission and security authority.', publishedDate: '2026-08-17', body: body('What should an access coordinator verify before a Philippines-based employee receives a new system permission?', 'access support is safer when it links the named person, role need, approved request, system owner, duration, and review evidence without treating a manager’s request as automatic authorization.', 'employee access requests', ['A role title is not a permission grant. Record the business need and approved entitlement separately, because titles can be stale or broader than the actual work lane.', 'Temporary access needs an end date and owner. A coordinator can track expiry and collect confirmation, but should not extend access because a task is unfinished or remove a control to meet a deadline.'], 'Security architecture, data sensitivity, incident response, and permission decisions depend on the employer’s systems and policies.', [sources.nist, sources.ftc, sources.cisa]) },
  { slug: 'philippines-employee-review-cycle-records-research', title: 'Philippines Employee Review-Cycle Records: Evidence Without Performance Judgments', excerpt: 'Research review-cycle administration that preserves dates, inputs, and owner actions without turning coordination into a performance decision.', publishedDate: '2026-08-17', body: body('What can a Philippines-based review coordinator establish before a manager makes a performance decision?', 'review administration should make cycle dates, required inputs, acknowledgements, and open questions traceable while managers retain judgment over performance, feedback, and employment action.', 'employee review-cycle records', ['Completion is not the same as quality. Record whether a form was submitted, whether the owner reviewed it, and whether an employee response is pending; do not infer performance from an empty or late field.', 'A coordinator can identify missing evidence and protect the review schedule. They should not rewrite feedback, rank people, or summarize a disputed statement as an accepted fact.'], 'Performance practices, employee relations, accommodations, and disciplinary consequences are employer-specific and are not decided by this research.', [sources.ilo, sources.ftc, sources.nist]) },
  { slug: 'philippines-staffing-onboarding-exception-research', title: 'Philippines Staffing Onboarding Exceptions: Evidence Before a Start-Date Decision', excerpt: 'Assess onboarding exception records that reveal missing evidence while HR and hiring owners retain authority over start dates and terms.', publishedDate: '2026-08-17', body: body('Which onboarding exception evidence helps an owner decide whether a Philippines staffing start can proceed?', 'exception records are useful when they identify the missing item, source, risk, owner, and proposed next step without converting urgency into an unapproved employment or access decision.', 'staffing onboarding exceptions', ['A complete-looking packet can still contain a conflicting identity field, unsigned document, unapproved term, or unavailable account. Test for contradictions as well as missing fields.', 'A delayed item should be categorized by decision impact. The coordinator can show what is blocked and who can unblock it; HR or the hiring owner decides whether a start date, access, or work assignment changes.'], 'Start-date, employment, access, and document requirements vary by employer, provider, role, and jurisdiction.', [sources.ilo, sources.nist, sources.ftc]) },
];
