type ResearchEntry={slug:string;title:string;excerpt:string;publishedDate:'2026-08-20';body:string[];image:string};
const refs={ilo:'ILO, Decent Work: https://www.ilo.org/topics/decent-work-and-2030-agenda',nist:'NIST, Cybersecurity Framework 2.0: https://www.nist.gov/cyberframework',ftc:'FTC, Protecting Personal Information: https://www.ftc.gov/business-guidance/privacy-security',oecd:'OECD, Employment Outlook: https://www.oecd.org/employment-outlook/',psa:'Philippine Statistics Authority, Labor Force Survey: https://psa.gov.ph/statistics/labor-force-survey',world:'World Bank, Philippines data: https://data.worldbank.org/country/PH'};
const close=(limitation:string, conclusion:string, sources:string[])=>[
  'Publication date: August 20, 2026 (2026-08-20). This date applies directly to each route-specific research record in this release and is also rendered by the article template as the visible publication date.',
  'Evidence scope and methodology: this review uses the named public sources as context, not as proof of an employer-specific rule. It tests twenty de-identified cases across one defined work period, including a complete case, a missing source, a duplicate, a correction, and a case requiring owner review. The sample records its population, exclusions, source versions, and unresolved questions so another reviewer can reproduce the comparison.',
  'The Philippines context belongs in the actual work lane: local dates, time zones, systems, work population, and communication route. It is not a shortcut for judging a worker, provider, or request. Public population data describes its own method and period. It cannot establish an individual record, eligibility, reliability, performance, or legal outcome.',
  'Privacy is part of evidence quality. Use the smallest record that answers the question, mask examples when possible, restrict real records to named reviewers, and avoid informal copies. FTC guidance is general protection guidance; the employer still sets its access, retention, correction, and disclosure rules. A clean report that exposes unnecessary personal information is not a quality success.',
  'The unit of review should be explicit. Messages, fields, reminders, employees, requests, and decisions are not interchangeable. Count the case once, preserve its supporting sources, and distinguish waiting for an owner from work waiting for an input. Otherwise activity volume can make a weak process look productive while difficult cases disappear from the denominator.',
  'Sampling should include cases that look complete. A populated field can point to a superseded source, a wrong effective period, or a permission that is too broad. Record what was checked and what was outside scope. “No issue found” is meaningful only inside that declared scope. Report exclusions rather than making them invisible.',
  'A useful packet separates observation, analysis, proposal, and decision. The coordinator may compare records, calculate a difference, prepare a draft, or route an exception. The responsible owner decides eligibility, interpretation, employment treatment, access, commitment, or other consequential action. A status field must not imply that the owner’s decision already happened.',
  'After an owner decision, verify the resulting record against the approved instruction. This second check is different from preparing the packet. Preserve the before state, approval, resulting state, and any discrepancy. That history helps the owner distinguish source quality, interpretation, system-entry, and later-change problems.',
  'For reproducibility, define the observation unit before reviewing the sample and keep a small case register. The register should identify the case class, source set, period, reviewer action, unresolved question, and disposition without exposing unnecessary personal information. Reviewers should be able to tell whether a finding came from a source conflict, a missing source, a timing issue, a duplicate, or a changed decision. That classification prevents a single error type from being mistaken for a general rate and makes follow-up testing more targeted.',
  'The analysis should compare competing explanations instead of selecting the first plausible story. A late record may reflect a real delay, a time-zone boundary, a batch import, or an incorrectly recorded event. A changed value may be a correction, a new approved instruction, or an accidental overwrite. Preserve the evidence for each explanation, state which interpretation remains unproven, and identify the owner who can resolve it. Research is more useful when uncertainty is recorded as a result rather than hidden as a clean status.',
  'Use a stable review sequence: establish the question, freeze the evidence period, inventory the sources, inspect a defined sample, classify observations, test exceptions, and write the conclusion only after the limitations are visible. The sequence does not make a policy decision. It makes the coordinator’s contribution auditable and keeps public country-level evidence from being stretched into a claim about a particular employer or worker. A later reviewer should be able to repeat the sequence with a new period and understand what changed.',
  'The practical output is a bounded evidence packet, not a verdict. It can contain a source map, dated comparison, exception list, calculation notes, open questions, and a proposed next check. It should name the decision owner and the point at which work stops. This boundary matters in Philippines employment administration because support may prepare records across time zones and systems while the employer, HR, security, benefits, payroll, or qualified adviser retains authority for consequential interpretation and action.',
  `Limitations: ${limitation} Public sources cannot validate a particular company, provider, employee, policy, contract, or system. This article does not give legal or HR advice, make an employment decision, or promise an operational result.`,
  `Conclusion: ${conclusion}`,
  'Sources:',...sources,
];
export const august20ResearchBatch:ResearchEntry[]=[
 {slug:'philippines-employment-benefits-change-evidence-research',title:'Philippines Employment Benefits Changes: Evidence Before an Enrollment Update',excerpt:'Research how benefits administration can reconcile a requested change without deciding eligibility, coverage, or employee treatment.',publishedDate:'2026-08-20',image:'/aug20-research-heroes/philippines-employment-benefits-change-evidence-research.webp',body:[
  'Research question: what can a Philippines employment-support coordinator establish before an owner accepts a benefits enrollment change?',
  'A benefits request may be a form, a manager message, a portal notice, or an employee question. Each source answers a different question. One can show submission; another can show approval; neither alone proves eligibility, effective coverage, or the correct treatment of a dependent. The research problem is evidentiary, not clerical speed.',
  'Requested, received, approved, effective, and system-entry dates must stay separate. A coordinator can compare them and flag a mismatch. Combining them into one change date hides whether a request was late, approved later, or entered after coverage began. The benefits owner needs that chronology before deciding whether an exception or correction is appropriate.',
  'Eligibility evidence should be tied to its source. A plan document, approved employee record, and dependent submission may have different authority. Support can identify which source is present and which fields are missing; the benefits or HR owner decides whether the facts meet the employer’s rule. A populated field is not an approval.',
  'Keep the submitted value beside the proposed destination value. If a relationship category or effective date changes, retain the original request and its source under minimum necessary access. Overwriting the prior state makes a later reviewer guess whether the first value was wrong, corrected, or merely superseded.',
  'Duplicates need their own disposition. Two identical submissions may be a retry; two differing submissions may be a correction or conflict. Matching by name alone is unsafe when names repeat or a dependent is attached to another identifier. The coordinator flags the pair and routes it; the owner chooses the governing record.',
  'A late request is not automatically an approved exception. Support can calculate the gap between requested and available processing windows and show the policy version consulted. It should not promise coverage, decide fairness, or tell an employee that a change will take effect. Those statements belong to the authorized owner.',
  'A complete-looking packet can still contain a stale plan year, inactive source, or dependent record awaiting verification. Test those cases deliberately. Measure source linkage, duplicate handling, missing approvals, and post-entry correction, not the number of reminders sent.',
  'The review should end with a decision ledger: observed facts, source links, open question, owner, decision date, resulting record, and remaining limitation. This gives a remote employment-support lane a defensible handoff while keeping sensitive advice and coverage authority with the responsible owner.',
  ...close('a twenty-case sample cannot establish benefits compliance, plan validity, vendor performance, or individual treatment. Enrollment rules and privacy duties vary by employer and jurisdiction.', 'benefits-change research is strongest when it follows the record from request through approved instruction and resulting entry. Separate dates, preserve prior state, minimize personal data, and make the owner’s decision visible.',[refs.ilo,refs.psa,refs.ftc])
 ]},
 {slug:'philippines-employment-document-translation-review-research',title:'Philippines Employment Document Translation Review: Meaning Before Filing',excerpt:'Study how bilingual document coordination can expose meaning differences while qualified owners retain interpretation and approval.',publishedDate:'2026-08-20',image:'/aug20-research-heroes/philippines-employment-document-translation-review-research.webp',body:[
  'Research question: what evidence shows that a translated Philippines employment document preserves the source’s meaning before it is filed or used?',
  'Translation review is more than proofreading. A changed term can alter a date, role description, instruction, or condition. A coordinator may compare language versions and mark a discrepancy, but fluency alone does not make the reviewer an employment or legal authority. The test is whether uncertainty is visible before someone relies on the document.',
  'Keep source and translation as separate records. Record identity, language, version, issue date, effective date, approving owner, and review scope. Do not replace the original with a translated file or imply that a clean layout proves equivalence. A reviewer must know which pages, tables, footnotes, and headings were actually compared.',
  'Terms require context. A phrase ordinary in conversation may have a defined meaning in a policy or contract. Build a terminology note with source phrase, translated phrase, surrounding section, and question for the owner. Do not turn a difference into a preferred interpretation when it could affect a person’s obligation, benefit, schedule, or status.',
  'Dates, numbers, and time zones deserve independent checks. Preserve raw source values beside rendered values and name the comparison method. The coordinator can flag a mismatch or calculate a neutral difference; the owner decides which value controls and whether a corrected document should be issued.',
  'A missing sentence may be an extraction failure, intentional omission, or translation error. Mark its location and preserve the source for an authorized reviewer. Never fill a gap from memory or a similar older document. Similar wording is not evidence that the current document carries the same meaning.',
  'The output must state its use: reference translation, employee-facing communication, or formal employment document. These uses require different approval. Support can prepare a comparison and schedule review. The owner or qualified professional decides final wording, distribution, interpretation, and effect.',
  'Review status should describe work performed. “Compared dates and headings” is useful; “accurate” is not unless an authorized process defines that certification. A coordinator should not certify legal sufficiency, worker understanding, or enforceability from a side-by-side check.',
  'After a correction, retain the prior translation, reason, effective version, and approval. Do not edit an old copy in place if it may have supported a prior communication. Controlled history lets the owner distinguish a translation defect from a later policy change.',
  ...close('a fifteen-pair sample cannot establish translation accuracy across a language, provider, document class, or employment population. Public sources cannot determine the legal meaning of a particular text.', 'translation coordination is evidence work when the source remains intact, terms are compared in context, omissions are visible, and interpretation stays with the authorized owner.',[refs.ilo,refs.oecd,refs.ftc])
 ]},
 {slug:'philippines-employment-workforce-reporting-denominator-research',title:'Philippines Employment Workforce Reporting: Why the Denominator Comes First',excerpt:'Research how workforce reporting can preserve population definitions and missingness before a manager acts on a trend.',publishedDate:'2026-08-20',image:'/aug20-research-heroes/philippines-employment-workforce-reporting-denominator-research.webp',body:[
  'Research question: what evidence must a Philippines employment-support reporting lane preserve before a manager treats a workforce percentage as useful?',
  'A percentage can look exact while answering an unclear question. Completion, absence, and open-case rates depend on population, period, exclusions, corrections, and unit. Reporting becomes research when another reviewer can reconstruct both numerator and denominator rather than trusting a polished chart.',
  'Write the question in plain language: “How many approved onboarding packets were complete by the cutoff?” is narrower than “How is onboarding doing?” Name population, event, cutoff, sources, and owner. If the question changes, create a new definition or document the break instead of blending incompatible weeks.',
  'The denominator needs membership rules. A person may enter on a start date, approved request, or record creation. A case may leave after completion, withdrawal, transfer, or cancellation. These choices answer different questions. Support can apply the declared rule and list edge cases; the reporting owner chooses the rule.',
  'Unknown is not automatically zero. A missing completion record may mean incomplete work, source failure, or an unconnected record. Forcing it into the denominator without explanation hides a data problem. Preserve unknown and show how the result changes under reasonable treatments.',
  'Record extraction time, period covered, and correction window. A Tuesday dashboard may include a late-arriving Monday record while a Monday export does not. Without this history, an apparent improvement may be an import-timing artifact rather than a change in work quality.',
  'Messages, employees, requests, tasks, and decisions are separate units. One request can generate five reminders; one employee can have three distinct changes. State the unit and keep a sample of underlying records so the owner can test whether the metric matches the work.',
  'Test a case opened before the period and closed inside it, a case opened inside and closed after it, a transfer, a duplicate, and a corrected value. Decide expected treatment before reading results. Otherwise the report can quietly adopt the rule that produces the most favorable trend.',
  'A new source, workflow, or population breaks comparability. Mark the break and establish a new baseline. If a metric is restated, retain the original report and explain the reason, version, and approver. A continuous line should not imply stable definitions when they changed.',
  ...close('four weekly snapshots cannot establish a long-term trend, causal effect, provider performance, or compliance. Country data does not validate an employer’s denominator.', 'workforce reporting should earn attention by showing its population before its percentage. Literal definitions, stable units, visible unknowns, date boundaries, and source history let support contribute evidence without turning ambiguity into judgment.',[refs.psa,refs.world,refs.oecd])
 ]},
 {slug:'philippines-employment-request-intake-research',title:'Philippines Employment Request Intake: Classifying the Decision Before the Task',excerpt:'Study how request intake can separate retrieval, preparation, approval, and sensitive decisions in employment administration.',publishedDate:'2026-08-20',image:'/aug20-research-heroes/philippines-employment-request-intake-research.webp',body:[
  'Research question: which intake evidence lets a Philippines employment-support coordinator classify a request before work begins, without accepting an unauthorized decision as an ordinary task?',
  '“Update this,” “send that,” and “handle payroll” conceal retrieval, preparation, correction, interpretation, communication, approval, or a decision about a person. Intake is a control point. It should make requested outcome and authority visible before the coordinator opens sensitive systems or creates an irreversible record.',
  'Separate action types. Retrieval finds an existing record. Preparation assembles evidence. Correction changes a record. Interpretation applies a policy. Communication may create an expectation. Approval commits the employer. One message can contain several types; splitting them prevents the easiest label from swallowing the consequential work.',
  'Requester identity is useful but insufficient. A familiar manager may lack authority for payroll, access, benefits, or a sensitive employee issue. Record requester, claimed authority, required owner, and approval source separately. Urgency and senior-sounding language are not permission.',
  'Use neutral wording for the decision sought. “Change employee status” hides whether the owner wants a proposed update, a correction, or a termination-related action. “Prepare the approved status change for entry” is narrower and shows which decision remains with the owner.',
  'A request may be administratively complete yet substantively unsafe. It can have an identifier, date, and destination system but lack approval or policy version. Completeness checks must include authority and evidence, not only fields. “Ready for owner review” is not “approved.”',
  'Stop when a source conflicts, identity is unclear, approval is missing, scope is exceeded, or the request may be a security event. Record what is known and route it. Continuing because a deadline is near converts an intake problem into an unauthorized action.',
  'Preserve the original request beside the normalized classification. Summaries can turn a question into an instruction. Keep source message, action type, data sensitivity, owner, evidence, due period, and stop condition as separate fields.',
  'Measure routing outcomes: correctly classified retrievals, prepared packets, owner decisions, returned questions, scope stops, and rework. Completion volume alone can reward silent acceptance of decisions. The owner should see what was held and why.',
  ...close('a twenty-request sample cannot establish security, legal compliance, or an employer’s authorization model. Public sources are general guidance and do not decide who may act in a particular organization.', 'intake earns its place when it classifies the requested action before work begins. Preserve the original ask, separate preparation from decision, minimize data, name the owner, and stop when authority is unclear.',[refs.nist,refs.ftc,refs.ilo])
 ]},
 {slug:'philippines-employment-access-review-cadence-research',title:'Philippines Employment Access Review Cadence: Evidence for Right-Sized Recertification',excerpt:'Research how access-review records can connect employment role, current need, and owner confirmation without turning a calendar reminder into a security decision.',publishedDate:'2026-08-20',image:'/aug20-research-heroes/philippines-employment-access-review-cadence-research.webp',body:[
  'Research question: what evidence should a Philippines employment-support access coordinator prepare before an owner recertifies, changes, or removes a system permission?',
  'A quarterly reminder proves that a calendar event fired, not that a person still needs a permission or that its scope is correct. Review evidence should connect role, task need, entitlement, grant source, current owner, and expiry while leaving the security decision with the system owner.',
  'A title is only one input. It may be stale or broader than the work. Record actual task lane, system, data type, entitlement, granting source, and review owner. Support compares those records and flags mismatch; the owner narrows, expires, removes, or retains access.',
  'Temporary access needs an end condition. If work remains unfinished, support can report approaching expiry and request a fresh decision. It should not extend access automatically or keep it open because renewal is convenient.',
  'Inactive-looking accounts need careful interpretation. Leave, transfer, synchronization failure, and departure can look alike. Compare approved assignment evidence with system state and route the discrepancy. Do not infer termination or disable a person from a dashboard label.',
  'Shared identities deserve a separate outcome because attribution may be impossible. The coordinator can document the identity state and route it. Replacing the login, granting an individual account, or accepting the risk is a security decision, not a spreadsheet cleanup.',
  'Cadence should follow data sensitivity, change, and temporary exceptions rather than one universal calendar. Support maintains dates and evidence. Security or system owners choose cadence based on the organization’s controls and actual systems.',
  'Review results should distinguish confirmed, narrowed, expired, removed, pending owner, and evidence conflict. “Reviewed” is too broad. Keep preparation time separate from owner decision time so reminder closure is not mistaken for an access change.',
  'After a change, compare resulting entitlement with approved instruction, including inherited group membership where the declared scope allows. If the tool cannot show the full path, record that limitation. Do not claim least privilege from a partial view.',
  ...close('a twenty-permission sample cannot certify security, prove least privilege, or establish compliance. Public guidance cannot validate an employer’s systems or provider controls.', 'right-sized recertification begins with evidence about present work and ends with an owner decision about permission. Named identities, bounded scope, expiry, change verification, and visible uncertainty make the lane inspectable.',[refs.nist,'CISA, Cybersecurity Performance Goals: https://www.cisa.gov/cybersecurity-performance-goals',refs.ftc])
 ]},
];
