export type October2ResearchPost={slug:string;title:string;excerpt:string;publishedDate:'2026-10-02';image:string;body:string[];handoff:{href:string;label:string;body:string}};

const candidate:string[]=[
`Research question. When two sourcing channels present the same candidate, what evidence lets a hiring owner resolve the conflict without allowing a coordinator to decide candidate ownership, fees, or selection? This study treats duplicate representation as a provenance problem. It does not assume that the first email, first database timestamp, or most complete profile creates a valid commercial claim.`,
`Why the question matters. A duplicate can arrive through an employee referral, an agency, a job board, a direct application, or a dormant talent record. Silently merging records can destroy consent and channel history. Leaving every record active can produce contradictory messages and count one person several times. The useful outcome is a traceable case that the authorized owner can decide, not an automated winner.`,
`Unit and sample. Use one fictional person token and every observed presentation of that token to one requisition. Construct 120 cases across direct applications, referrals, two agencies, a talent community, a reopened requisition, and a confidential replacement. Include transliterated names, changed emails, shared phone numbers, an agency submission after a direct application, simultaneous events, and earlier interest in another role. All identities and documents remain synthetic.`,
`Capture each presentation as its own event. Required fields are channel, sender, received instant, claimed event instant, requisition identifier and version, stated permission, attached terms, contact details, communications already sent, and the information visible at that time. Preserve the submitted artifact and hash. Do not copy a later interpretation into an earlier event or collapse unknown, not supplied, disputed, and not applicable into blank.`,
`Identity matching remains a hypothesis. Compare stable tokens where available, then apply an approved rule to combinations of contact points and candidate-confirmed context. A similar name must not trigger a merge. A matching address can still represent a shared or recycled mailbox. Record probable duplicates separately until an authorized reviewer accepts or rejects the relationship, and retain the evidence that supported the original classification.`,
`Build a provenance graph instead of a winner column. Nodes represent submissions, consent events, requisition versions, pauses, and communications. Edges state why records may describe one person or relate to one search. The graph must expose missing consent, an unknown requisition, expired commercial terms, or an assertion that cannot be corroborated. Restrict the view to fields needed for the declared review purpose.`,
`Sequence test. Replay the queue by received time and again by verifiable event time. An agency may upload first while a direct application happened earlier; a referral may be logged late; a scheduled integration may create an apparently old record. Measure how often “earliest system timestamp” disagrees with the complete chronology, whether outreach stops while facts are disputed, and whether the responsible owner receives the unresolved alternatives.`,
`Purpose test. For every node, record the declared purpose and candidate-facing evidence supporting it. Do not infer permission to submit someone to a new opening from a prior conversation about another job. The Philippine Data Privacy Act’s transparency, legitimate-purpose, proportionality, accuracy, currency, security, and retention principles frame the controls. They do not settle a representation dispute or prove a particular submission lawful.`,
`Decision boundary. Coordinators may detect likely duplication, pause parallel outreach under an approved rule, assemble chronology, ask authorized factual questions, and route the case. Hiring and commercial owners decide representation, contractual priority, fees, channel exceptions, and next contact. Count a coordinator-made ownership ruling as a serious boundary failure even when the owner later reaches the same result. Correct guesses are still unauthorized decisions.`,
`Candidate-experience trial. Seed one case where three channels contact the person within an hour, one where a pause reaches only an agency, and one where a merge hides the preferred contact route. Observe message count, contradictory instructions, response burden, correction time, and time to a single accountable contact. Faster internal closure is not success if duplicate or misleading outreach continues.`,
`Controlled comparison. Process half the cases with a timestamp-ordered deduplication queue and half with the provenance graph plus pause state. Keep staff, information, and time equal. Compare detected duplicates, false merges, parallel outreach after detection, unsupported ownership rulings, missing acknowledgments, owner response time, and candidate-facing corrections. Report counts and denominators; do not let a favorable average hide a wrongful merge.`,
`Adversarial cases include two different people with the same name, one person using a preferred name, a referral copied from a public profile without confirmed contact, an agency claim lacking a requisition, and a direct application received while the opening was paused. Add a merged record later proven false. The procedure must unwind that merge without rewriting the original trail or exposing one person’s record to another.`,
`The owner packet contains a compact chronology, identity-match confidence and basis, purpose and permission evidence, applicable channel terms supplied by their owners, communications already sent, unresolved facts, and the next reversible action. It must not rank the candidate or recommend which commercial claim to honor. A separate event captures the accountable owner’s decision, rationale, scope, and recipients.`,
`Privacy review inventories views, downloads, notifications, search indexes, integration caches, and deletion or correction paths. Candidate identifiers stay out of general dashboards. Temporary access expires. Rejected match hypotheses receive a defined retention treatment. If unexpected real data enters the exercise, testing stops and follows the approved incident route rather than copying the material into a defect report.`,
`Interpretation separates observations, match classifications, owner decisions, and researcher inference. A high detection rate is useful only beside false-merge and excess-contact rates. A low conflict count could mean good routing, missed detection, or suppressed reporting. When evidence cannot establish identity, sequence, or permission, the defensible result is uncertainty with a named owner and a stop condition.`,
`Limitations. Synthetic cases cannot establish a candidate’s intent, interpret agency contracts, authorize processing, or decide selection. They can show whether a proposed coordination service preserves facts and respects the decision boundary. A buyer should request a sanitized duplicate register, pause control, candidate correction path, access log, and owner acknowledgment, then begin with a narrow approved pilot.`,
`Sources checked October 2, 2026: National Privacy Commission, “Republic Act 10173 — Data Privacy Act of 2012,” https://privacy.gov.ph/data-privacy-act/; National Privacy Commission, “The Data Privacy Act and Its IRR,” https://privacy.gov.ph/the-data-privacy-act-and-its-irr/; NIST, “Digital Identity Guidelines: Identity Proofing and Enrollment,” https://pages.nist.gov/800-63-4/sp800-63a/proofing/. NIST supplies technical concepts, not Philippine employment rules, and none of these sources proves provider performance.`
];

const documents:string[]=[
`Decision under study. An employment document may display the expected names while still being the wrong artifact. Can administration connect the owner-approved source, populated rendering, signature request, signer events, completed envelope, and released copy without interpreting terms or declaring a signature legally sufficient? The test examines chain integrity. It is not an opinion on electronic-signature law, contract formation, or enforceability.`,
`Define document families before testing: offer letters, policy acknowledgments, amendments, equipment forms, and role-change notices. For each, identify the wording owner, fields administrators may populate, signers, sequencing rule, expiry, release condition, and repository. Freezing that specification stops reviewers from redefining success after seeing which journeys fail and makes exceptions visible rather than informally accepted.`,
`Create 100 fictional journeys covering ordinary completion, rejection, expiration, resend, signer substitution, corrected email, withdrawn offer, changed start date, owner-controlled value change, bilingual attachment, duplicate envelope, missing annex, and completion after supersession. Use invented identities, terms, addresses, and amounts. Keep a hidden answer key containing intended file versions and permitted routes.`,
`A filename is not version evidence. Assign the approved source a stable identifier, explicit version, approval event, and cryptographic hash. Record a second hash after permitted field population and another for the file attached to the envelope. Rendering may legitimately change bytes, so retain the authorized relationship and transformation instead of asserting identical files when they are not identical.`,
`The pre-send drill seeds an approved source with an unapproved attachment, outdated clause, blank required field, and correct-looking filename copied over the wrong file. Administrators may detect and stop these conditions but cannot decide wording differences are immaterial. Score whether the issue reaches the document owner before a recipient sees it and whether correction creates a distinct, reviewable version.`,
`The routing drill gives two people similar names, changes one address after issuance, and introduces a delegate who is not an approved signer. Record the source of every address and signer role. Delivery proves only that a message reached an address. It does not establish identity, authority, comprehension, capacity, or a valid signature. Those conclusions remain with accountable owners and advisers.`,
`The event drill uses countersignature, parallel signature, and acknowledgment-only cases. Delay one event, replay a webhook, and complete an old envelope after its replacement is sent. The register distinguishes requested, viewed, signed, declined, expired, voided, superseded, completed, released, and cannot determine. A generic “done” status hides the very transitions a buyer needs to inspect.`,
`Portability matters after platform access changes. Export the completed file, certificate, event log, and approval record, then place the package in its designated repository. Verify that identifiers and hashes still connect. Rename a file, forward a copy, compress a download, and disable the original account. Determine which evidence remains understandable without treating a platform screenshot as permanent proof.`,
`Release is its own decision point. Completion does not automatically authorize distribution to every recipient or dependent system. The document owner defines whether completion, countersignature, review, or another event permits release. The administrator checks that declared condition, records recipients and time, and stops on conflict. Owners retain wording, exception, authority, and legal decisions.`,
`Compare filename-plus-status handling with full source-to-envelope lineage. Give each group equal tools and deadlines. Measure wrong-version sends, unapproved attachments, unsupported signer changes, completions on superseded envelopes, missing evidence, duplicate release, unnecessary disclosure, and time to owner resolution. Report severe events independently; one wrong-recipient disclosure cannot disappear inside a high completion percentage.`,
`Challenge silent correction. After issuance, change a display field in one case and an owner-controlled field in another. Staff do not judge materiality. The procedure preserves history, routes the difference, creates an owner-authorized replacement, communicates current state, and retains the relationship between withdrawn and replacement artifacts. A later clean file must not rewrite what the original recipient actually received.`,
`Search beyond the signing portal. Inspect the approved repository, email attachments, chat uploads, local downloads, browser copies, integrations, onboarding tasks, and backups. An envelope can be voided correctly in one place while a stale actionable copy survives elsewhere. Record every observed copy’s purpose, custodian, current state, retention basis, and correction or deletion acknowledgment.`,
`Useful measures include source-version coverage, source-to-envelope traceability, superseded completion, unsupported signer substitution, duplicate release, orphaned copies, owner-response time, and reviewer agreement. Every classification cites an event and version. Missing evidence remains missing; reviewers must not convert it to a negative answer merely to finish a dashboard.`,
`Privacy controls limit sensitive fields, provide role-specific views, expire temporary access, log exports, and verify revocation across dependent systems. Republic Act 10173’s declared-purpose, proportionality, accuracy, security, and retention principles guide the questions. They do not decide enforceability, signer authority, appropriate terms, or whether a real organization has satisfied its obligations.`,
`A successful pilot would show that the administrative process preserves approved versions, detects declared exceptions, and gives owners reviewable evidence. It cannot prove legal validity, fair terms, employment classification, or continuous compliance. Procurement should ask for a sanitized lineage record and a demonstration of superseded-envelope recovery before entrusting live documents.`,
`Sources checked October 2, 2026: National Privacy Commission, “Republic Act 10173 — Data Privacy Act of 2012,” https://privacy.gov.ph/data-privacy-act/; National Privacy Commission, “Implementing Rules and Regulations of the Data Privacy Act,” https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/; NIST, “Cybersecurity Framework 2.0,” https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20. These are control references, not findings about an envelope or provider.`
];

const schedules:string[]=[
`Operating question. A Philippines-based employee may work across midnight while collaborating with a team in another timezone. What must schedule administration preserve so a manager can resolve coverage, approval, and attendance questions without the coordinator interpreting rules or altering time records? The inquiry focuses on handoffs where clocks and calendar dates disagree, not on whether a schedule is lawful or desirable.`,
`Map time explicitly. Every event needs the schedule timezone, counterpart timezone, display timezone, UTC instant, offset, and relevant local date. Store the IANA timezone identifier and observed offset rather than reconstructing them from an abbreviation later. The Philippines does not observe daylight saving time, while a counterpart location may change its offset during the same recurring Manila schedule.`,
`Construct 96 fictional shift sequences spanning Manila, Sydney, London, New York, and UTC displays. Include overnight work, breaks, approved swaps, emergency extensions, partial leave, holiday labels, system maintenance, missed acknowledgments, and counterpart daylight-saving transitions. Use invented workers and teams. Exclude health, family, performance, disciplinary, and other details unnecessary for schedule coordination.`,
`Start from the authorized schedule. Record version, approving owner, effective interval, local start and end, timezone identifier, break convention, coverage expectation, and required recipients. A calendar invitation is not automatically authoritative. A recurring meeting can preserve an obsolete offset, and a copied spreadsheet can omit the effective date that distinguishes the current pattern from its replacement.`,
`Replay one shift as knowledge arrives. Release an authorized pattern, then reveal a swap request, manager approval, delayed system synchronization, and counterpart calendar update. Reviewers state what was known at every instant. This prevents a late approval from making an earlier action appear authorized and shows whether each downstream display received the same version.`,
`The midnight scenario starts at 22:00 Asia/Manila and ends at 07:00 the following day, with leave and a handoff at 00:30. Systems label it by start date, end date, payroll date, or calendar day. Administration records each convention and conflict. Managers, HR, payroll, policy owners, and advisers determine which rule governs a real consequence.`,
`The daylight-saving scenario holds Manila hours fixed while New York changes offset. One calendar adjusts, one spreadsheet does not, and a message says only “9 a.m. Eastern.” Reviewers identify the applicable instant, ambiguity, affected coverage, and owner. They may not guess which party should absorb the change or modify the authorized schedule to make displays agree.`,
`An interruption scenario removes the scheduling platform before a swap, delays the manager response, and leaves an informal agreement in chat. The contingency register preserves last-known authorized state, marks the request unresolved, captures the later decision, and reconciles dependent systems without producing two active schedules. Convenience, memory, or repeated behavior does not become authorization.`,
`Boundaries remain explicit. Coordinators maintain schedule versions, collect approvals, reconcile displays, flag coverage gaps, and route exceptions. Managers, HR, payroll, legal, and policy owners decide work requirements, leave treatment, compensation, attendance consequences, holiday application, and exceptions. An administrative inference on one of those questions counts as a boundary failure even if operationally convenient.`,
`Compare a shared calendar plus messages against a versioned schedule with explicit timezones, effective instants, acknowledgments, and a conflict queue. Measure stale-version use, incorrect instant conversion, duplicate coverage, uncovered periods, unacknowledged changes, unauthorized decisions, and time to confirmed handoff. Randomize cases and hold staff, tools, and time constant.`,
`Inspect paths beyond the primary calendar: workforce software, email, mobile notifications, payroll-input staging, leave registers, dashboards, and exports. Record when each path receives a change and whether it retains timezone, version, and effective instant. A correct main screen cannot cure a stale notification or spreadsheet that people continue to follow.`,
`Analyze with a handoff matrix. Rows are coverage intervals in UTC; columns show owner, local display, schedule version, acknowledgment, dependent-system state, and open conflict. Highlight gaps and overlaps without declaring acceptable staffing. The matrix makes the manager’s choice visible while preserving the administrator’s narrower role as evidence custodian and exception router.`,
`Report conversion accuracy, version coverage, acknowledgment latency, unresolved age, stale-copy count, coverage gaps, false conflicts, and reviewer agreement. Separate problems caused by missing sources from conversion and propagation failures. Use medians and tails rather than one average. A rapid update without recipient acknowledgment remains incomplete and must not be reported as confirmed.`,
`Schedules reveal patterns about identifiable people. Collect only fields required for the declared test, restrict roster views, avoid reasons for leave, inventory exports, and retire temporary datasets. If real information appears, stop and follow the approved privacy route. Privacy principles guide handling but do not answer pay, leave, or working-time questions.`,
`This design cannot interpret labor law, determine overtime, approve leave, establish contractual hours, or set staffing levels. It can show whether a proposed service keeps time evidence intelligible and sends exceptions to accountable owners. Begin with one team, two patterns, named decision makers, and a written stop rule before expanding the pilot.`,
`Sources checked October 2, 2026: National Privacy Commission, “Republic Act 10173 — Data Privacy Act of 2012,” https://privacy.gov.ph/data-privacy-act/; NIST, “Cybersecurity Framework 2.0,” https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20; IANA, “Time Zone Database,” https://www.iana.org/time-zones. They support privacy, governance, and timezone design questions, not employment or pay conclusions.`
];

const benefits:string[]=[
`Buyer question. When a benefits carrier rejects an enrollment transaction, can support staff reconstruct the exchange and route a correction without deciding eligibility, interpreting plan terms, or promising coverage? The research follows an outbound record through acknowledgments, rejection, correction, resubmission, and owner disposition so a favorable final status cannot erase the earlier failure.`,
`One test case contains a fictional worker token, benefit and plan identifiers, event reference supplied by its owner, approved effective date, outbound version, transport receipt, carrier response, code explanation, correction authority, resubmission, and final acknowledgment. Do not include diagnoses, claims, medical facts, actual dependent records, government identifiers, or live account information.`,
`Create 105 cases covering accepted enrollment, rejected dependent, invalid plan code, date mismatch, duplicate member, missing field, transport failure, file rejection, row warning, retroactive correction, termination collision, reopened case, and response arriving after a newer file. Seed obvious and ambiguous codes. Preserve a hidden answer key and randomize case order.`,
`Freeze each outbound package. Record field provenance, source versions, owner approvals for controlled values, export time, transport destination, and a content hash. A successful upload proves only that bytes reached an endpoint. It does not prove the carrier parsed every row, accepted enrollment, established eligibility, or made coverage available to the person.`,
`Model acknowledgment layers separately: transport receipt, file validation, transaction acceptance, warning, rejection, pending review, downstream confirmation, and cannot determine. Tie every state to source, observed time, and transaction version. A dashboard label must not overwrite a contradictory response file; both remain evidence until the responsible owner resolves their relationship.`,
`Review response codes with an approved dictionary carrying version and effective date. Include an undocumented code, a reused number, truncated explanation, and a meaning changed between dictionary versions. Support staff may retrieve documentation and identify discrepancies. Benefits and carrier owners decide interpretation, eligibility impact, correction, and any employee-facing conclusion.`,
`Trace correction field by field: rejected value, originating record, proposed value, approving authority, editor, time, and replacement payload. When the source is wrong, route it rather than patching only the carrier file. When mapping is wrong, preserve the source and change the controlled mapping. This distinction prevents the next export from restoring the defect.`,
`Seed an accepted-looking response with an unexpected effective date, a dependent under another identifier, and a retroactive file colliding with termination. Administration may surface differences and collect evidence. It must not choose entitlement, waive rules, pick a date, approve deductions, or state coverage. Those remain accountable decisions outside the coordination lane.`,
`Have a fictional employee ask whether coverage exists while the response is pending. The correct administrative message follows approved wording, states known facts, avoids promises, names the decision owner, and records the inquiry. Score unsupported assurance as a serious failure separate from response time, since a fast but false answer is not good service.`,
`Compare a latest-status spreadsheet with a transaction-lineage register. Measure orphaned rejections, corrections lacking authority, wrong-version resubmission, code misclassification, false closure, duplicate transmission, overstatement to employees, owner-resolution time, and final acknowledgment coverage. Give both groups equal information and deadlines, and disclose excluded or indeterminate cases.`,
`Reconcile in both directions. Starting from every source enrollment, locate its carrier result; starting from each result, locate the source transaction. Investigate one-to-many and many-to-one matches. Totals can balance while hiding one duplicate and one omission, so record-level linkage and unmatched-item aging are necessary before the owner receives a completion claim.`,
`Push a correction through the benefits platform, carrier portal, payroll-deduction staging, employee communication queue, case tracker, and exports. Record which systems accept the new version and which retain the old one. Updating the primary screen is insufficient when another recipient can still act on stale data; every unresolved path needs an owner and honest status.`,
`Report acceptance by version, rejection class, unresolved age, authorized-correction coverage, resubmission count, duplicate rate, propagation acknowledgments, inquiry quality, and reviewer agreement. Keep observed facts, dictionary classifications, owner decisions, and researcher inference in distinct fields. Sampling claims need denominators and limitations. Serious boundary events remain visible outside aggregate success scores.`,
`Use synthetic tokens and masked values, purpose-specific views, expiring access, download inventories, and verified restriction or deletion in derivatives. The Data Privacy Act’s accuracy, purpose, proportionality, security, and retention principles frame data handling. They do not establish eligibility, coverage, lawful deductions, contract meaning, or the right resolution for an actual case.`,
`A pilot can test whether support preserves transaction evidence and escalation boundaries. It cannot establish plan performance beyond the sample or decide employee rights. Procurement should ask for a sanitized rejection-to-resolution chain, code-dictionary governance, access evidence, and an employee-query demonstration before processing an approved low-risk test population.`,
`Sources checked October 2, 2026: National Privacy Commission, “Republic Act 10173 — Data Privacy Act of 2012,” https://privacy.gov.ph/data-privacy-act/; National Privacy Commission, “Implementing Rules and Regulations,” https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/; NIST, “Cybersecurity Framework 2.0,” https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20. These provide general controls, not plan or eligibility findings.`
];

const corrections:string[]=[
`Research objective. When an employee disputes a factual record, what evidence should records administration preserve from intake through owner decision, correction, and downstream notification? The study asks whether a team can coordinate the request without deciding legal rights, changing owner-controlled facts, or claiming that every recipient corrected its copy before verification exists.`,
`Build each case around one disputed element rather than an entire file. Use a fictional worker token, field name, current value, source and version, stated dispute, identity-check outcome supplied by its owner, decision owner, correction instruction, known recipients, dependent systems, and acknowledgments. Narrow scope reduces unnecessary access while keeping propagation testable.`,
`Assemble 90 synthetic cases across contact details, emergency-contact relationship, preferred name, work location, manager assignment, start date, training status, and document metadata. Include correct records challenged without supporting evidence, incorrect sources copied widely, disagreeing sources, multi-field requests, an unauthorized requester, and a correction later reversed. Never use live employee information.`,
`Intake is a routing event. Capture request time, channel, exact field, requested outcome, supplied evidence, declared urgency, and notice to the requester. Do not paste a free-form personal narrative into every downstream ticket. Keep identity or authority checks distinct from the correction merits; responsible privacy and records owners define those processes and outcomes.`,
`Map provenance before editing. Identify the approved source, transformations, recipients, and versions for the disputed field. Mark unknown paths rather than assuming the HR platform is authoritative. A downstream display may faithfully reproduce a stale source, while the source itself may contain an error. Those are distinct failure classes and must reach different owners.`,
`Coordinators acknowledge intake, collect specified evidence, map copies, preserve current state, apply an owner-approved instruction, notify named recipients, and chase acknowledgments. HR, privacy, legal, security, payroll, management, and system owners determine identity, accuracy, rights, disclosure, exceptions, and the authoritative value. A plausible inference does not expand the coordinator’s authority.`,
`Before an approved change, retain only the necessary prior value, source, version, restriction, and supersession reason under the owner’s rule. Preservation is not permission for unlimited shadow copies. Authorized reviewers may need old and new states, while ordinary users may need only the current value. Test whether access changes accordingly after the decision.`,
`Use a recipient graph spanning the HR record, directory, payroll-input staging, benefits file, learning system, manager roster, email group, reporting warehouse, search index, and three exports. Release acknowledgments at different times. One system rejects the change, one requires mapping repair, and one turns out to be outside the approved purpose.`,
`Distinguish instruction sent, receipt, validation, applied version, observed value, rejection, and follow-up owner. An email saying “updated” does not prove a dependent system applied the correction. Conversely, a system without callbacks may require an approved manual check rather than an unsupported failure assumption. Unknown remains a valid state until evidence changes it.`,
`Seed an employee-supplied value, manager update, and source-system event close together. Administration does not choose among them. It freezes chronology, prevents blind overwriting, and routes the conflict. After the owner decides, the new instruction references superseded instructions so a delayed integration cannot silently restore a stale value.`,
`Compare a primary-system update plus informal emails with the provenance and recipient graph. Measure unauthorized edits, missed recipients, stale reappearance, excess disclosure, false completion, owner-decision time, verified propagation time, and residual unknown paths. Use identical cases and time windows. Preserve first-run evidence before correcting the workflow and repeating affected scenarios.`,
`Test requester communications for received, identity review pending, owner review, correction approved, correction declined, partial propagation, and closure with residual limitations. Each message distinguishes observed facts from owner decisions and avoids needless recipient detail. Score false assurance, inconsistent wording, disclosure, and unexplained silence alongside timeliness.`,
`Run a recovery scenario by restoring a stale backup, replaying an old integration message, and discovering an offline export after closure. Observe detection, containment, reapplication, owner notification, and evidence preservation. Recurrence becomes a linked new event; staff must not quietly edit the original closure timestamp or conceal the failed downstream control.`,
`Analysis uses several clocks: intake to acknowledgment, intake to owner decision, instruction to receipt, receipt to verified application, and age of unresolved paths. Also report source coverage, recipient discovery, unauthorized access, recurrence, communication accuracy, and reviewer agreement. Averages cannot hide a high-risk stale copy; counts always include denominators and exclusions.`,
`Republic Act 10173 supplies accuracy and correction concepts alongside purpose, proportionality, security, and retention principles. NIST identity guidance helps separate evidence collection, validation, and verification. Apply them as research inputs while leaving legal interpretation and real decisions to accountable owners and qualified advisers. Neither source proves that a workflow complies.`,
`Synthetic testing cannot determine whether a request must be granted, which source is legally authoritative, whether identity was established, or whether retention is justified. It can reveal whether administration maintains reviewable lineage and honest status. Procurement should request a sanitized register, recipient map, access view, and stale-recurrence drill before a limited approved pilot.`,
`Sources checked October 2, 2026: National Privacy Commission, “Republic Act 10173 — Data Privacy Act of 2012,” https://privacy.gov.ph/data-privacy-act/; National Privacy Commission, “The Data Privacy Act and Its IRR,” https://privacy.gov.ph/the-data-privacy-act-and-its-irr/; NIST, “Digital Identity Guidelines: Identity Proofing and Enrollment,” https://pages.nist.gov/800-63-4/sp800-63a/proofing/. Sources frame controls, not findings about a provider or request.`
];

const expand=(subject:string)=>[
`Calibration for ${subject}. Two reviewers independently handle unseen edge cases and cite the exact evidence behind each classification. Disagreement becomes a finding about definitions, access, or source quality rather than a training score. Preserve both attempts, let the accountable owner clarify the rule, version that change, and retest with new cases so familiarity cannot masquerade as repeatability.`,
`Recovery challenge for ${subject}. Remove a required source, delay an acknowledgment, replay an obsolete event, and interrupt the primary system. Observe whether the routine preserves last-known state, prevents double action, exposes uncertainty, and resumes without rewriting history. Record affected downstream copies and named recovery owners until each is verified or honestly remains unresolved.`,
`Evidence review for ${subject}. Trace every sampled outcome backward to its source and forward to recipients. Distinguish observed fact, rule classification, researcher inference, and owner decision. Missing evidence stays missing. Measure coverage, exception age, access scope, propagation, and agreement with explicit denominators, while reporting serious boundary failures outside any aggregate score.`,
`Acceptance for ${subject}. Set thresholds before opening the hidden answer key, including zero tolerance for unauthorized substantive decisions and avoidable sensitive-data exposure. A corrected outcome does not erase its first-pass failure. Change the control through its owner, retain the initial record, and demonstrate improvement only on a fresh blinded sample that includes adverse cases.`,
`Procurement use for ${subject}. Ask the provider to demonstrate a sanitized register, version history, permission view, exception route, recipient acknowledgment, and audit export. A polished demo or policy is point-in-time evidence, not proof of continuing operation. Begin live work with a narrow approved population, least privilege, named reviewers, monitored exceptions, and a stop rule.`,
`Decision brief for ${subject}. Present the buyer with the observed result, denominator, excluded cases, uncertainty, operational consequence, control cost, and accountable next decision. Include the strongest alternative explanation and the evidence that supports or weakens it. Avoid a single maturity label that blends boundary violations with ordinary delays. A useful recommendation identifies what can be delegated now, what must remain with the owner, which evidence is absent, and the next bounded test. The conclusion expires when a material source, system path, role boundary, or process version changes, so record the applicable scope and review trigger.`
 ,`Limit the claim for ${subject} to the tested population, systems, versions, recipients, and observation window. Describe exclusions and cases that could not be determined. A passing result supports a cautious pilot decision; it does not guarantee future performance, legal compliance, security, employee outcomes, or accuracy outside the sample. Schedule review when ownership, source definitions, integrations, or access patterns change.`
];

export const october2ResearchBatch:October2ResearchPost[]=[
 {slug:'philippines-candidate-duplicate-representation-research',title:'How Should Duplicate Candidate Representation Be Researched?',excerpt:'A controlled study of duplicate submissions, match hypotheses, channel provenance, candidate contact, pause controls, and owner decisions.',publishedDate:'2026-10-02',image:'/aug20-research-heroes/philippines-employment-request-intake-research.webp',body:[...candidate,...expand('duplicate-candidate provenance')],handoff:{href:'/services/candidate-sourcing-coordination',label:'Plan candidate sourcing coordination',body:'Define channel authority, duplicate evidence, pause rules, and hiring-owner decisions before sourcing begins.'}},
 {slug:'philippines-employment-document-signature-envelope-integrity-research',title:'Can a Signature Envelope Be Traced to the Approved Employment Document?',excerpt:'Research on source versions, rendered files, signer routing, superseded envelopes, completion evidence, and controlled release.',publishedDate:'2026-10-02',image:'/aug23-research-heroes/philippines-employment-document-version-research.png',body:[...documents,...expand('signature-envelope integrity')],handoff:{href:'/services/employment-document-administration',label:'Plan employment document administration',body:'Map document approval, permitted preparation, signer routing, release authority, and evidence retention before issuance.'}},
 {slug:'philippines-overnight-schedule-timezone-handoff-research',title:'What Should an Overnight Schedule Handoff Preserve Across Timezones?',excerpt:'A study of schedule versions, local dates, UTC instants, foreign daylight-saving changes, acknowledgments, and owner boundaries.',publishedDate:'2026-10-02',image:'/aug21-research-heroes/philippines-employment-schedule-handoff-research.png',body:[...schedules,...expand('overnight schedule handoff')],handoff:{href:'/services/schedule-administration',label:'Plan schedule administration',body:'Specify timezone conventions, schedule authority, acknowledgments, dependent systems, and exception owners.'}},
 {slug:'philippines-benefits-carrier-rejection-lineage-research',title:'Can a Benefits Rejection Be Traced From Source to Resolution?',excerpt:'Research on outbound enrollment versions, layered acknowledgments, response codes, authorized corrections, resubmissions, and employee queries.',publishedDate:'2026-10-02',image:'/aug20-research-heroes/philippines-employment-benefits-change-evidence-research.webp',body:[...benefits,...expand('benefits rejection lineage')],handoff:{href:'/services/benefits-administration-support',label:'Plan benefits administration support',body:'Define source owners, response-code authority, correction approvals, communications, and carrier acknowledgments.'}},
 {slug:'philippines-employee-record-correction-propagation-research',title:'How Should an Employee-Record Correction Propagate?',excerpt:'A controlled study of disputed fields, source provenance, owner-approved corrections, recipient graphs, acknowledgments, and stale recurrence.',publishedDate:'2026-10-02',image:'/aug23-research-heroes/philippines-employment-record-timeline-research.png',body:[...corrections,...expand('record-correction propagation')],handoff:{href:'/services/employee-records-management',label:'Plan employee records management',body:'Agree intake, source authority, correction ownership, recipient mapping, access, and verification before changing records.'}}
];
