export type Sep14ResearchPost={slug:string;title:string;excerpt:string;publishedDate:'2026-09-14';image:string;body:string[]};
type Study=[string,string,string,string,string,string,string,string,string];
const studies:Study[]=[
['philippines-employment-owner-absence-handoff-research','What Makes an Owner-Absence Handoff Reviewable?','A synthetic comparison of status notes and bounded event-based handoffs.','/aug23-research-heroes/philippines-employment-record-timeline-research.png','Does a handoff with source, boundary, next action, and return condition reduce unsupported action compared with a short status note?','Create sixty synthetic cases with missing evidence, authority conflicts, changed deadlines, and valid routine work. Give two blinded groups either short notes or structured handoffs.','unsupported actions, correct holds, unnecessary holds, reviewer agreement, and review time','grant authority or decide pay, leave, access, eligibility, discipline, or policy exceptions','Live cases contain oral context, restricted evidence, and local rules that the synthetic set omits.'],
['philippines-partial-day-leave-reconciliation-research','Which Fields Reduce Partial-Day Leave Mismatches?','A synthetic study of dates, times, zones, units, and downstream records.','/aug21-research-heroes/philippines-employment-leave-chronology-research.png','Which field set helps reviewers detect a partial-day mismatch across an approval, calendar, time record, and payroll handoff?','Build seventy-two synthetic cases with explicit times, zones, units, and destination states. Seed transcription, rounding, full-day conversion, and delayed-update errors.','false clearance, correct mismatch detection, cannot-determine decisions, and review time','determine entitlement, balances, rounding policy, payroll treatment, or employee outcomes','The study excludes overnight shifts, changing schedules, regional holidays, and live personal data.'],
['philippines-benefits-return-file-reconciliation-research','Can Row-Level Reconciliation Catch Benefits File Returns?','A controlled synthetic test of transport receipts and provider row outcomes.','/aug20-research-heroes/philippines-employment-benefits-change-evidence-research.webp','Does row-level reconciliation reduce false acceptance when a provider receives a file but returns some records?','Generate fifty synthetic files with accepted transport receipts. Seed accepted rows, missing identifiers, invalid dates, duplicates, and pending provider questions.','false acceptance, missed returned rows, unnecessary resubmission, agreement, and time per file','determine eligibility, coverage, contributions, effective dates, or provider obligations','Provider codes and formats vary, and synthetic error frequencies cannot estimate live failure rates.'],
['philippines-workforce-filter-version-research','How Much Can a Filter Version Change a Workforce Measure?','A sensitivity protocol that separates population definitions from record movement.','/aug20-research-heroes/philippines-employment-workforce-reporting-denominator-research.webp','How often does a changed inclusion filter move a synthetic measure across a declared threshold when source records stay fixed?','Construct forty-eight monthly datasets, then apply paired filters that alter status, location, worker type, or effective-date treatment. Preserve each query version.','denominator changes, absolute and relative movement, threshold crossings, and reproduction errors','choose the correct population, interpret results, set materiality, or authorise a restatement','The datasets omit many joins, late records, privacy constraints, and correction histories.'],
['philippines-employment-service-clock-pause-research','Do Defined Pause Reasons Improve Service-Time Review?','A blinded synthetic comparison of raw event logs and governed pause records.','/aug20-research-heroes/philippines-employment-response-time-research.png','Can declared pause reasons improve reproduction of adjusted service time without hiding raw elapsed time?','Create eighty synthetic timelines with active work, missing evidence, owner review, provider waits, outages, invalid pauses, and late restarts.','calculation error, invalid-pause acceptance, correct escalation, reviewer agreement, and time','set service targets, excuse delays, judge employee impact, or decide whether a pause is fair','Live logs may contain disputed timestamps, overlapping pauses, clock changes, and incomplete migrations.'],
];
const references='References: National Institute of Standards and Technology, Cybersecurity Framework 2.0 (https://doi.org/10.6028/NIST.CSWP.29); National Institute of Standards and Technology, Privacy Framework 1.0 (https://doi.org/10.6028/NIST.CSWP.01162020); U.S. Government Accountability Office, Standards for Internal Control in the Federal Government, GAO-14-704G (https://www.gao.gov/products/gao-14-704g); Philippine Statistics Authority, Annual Survey of Philippine Business and Industry (https://psa.gov.ph/statistics/annual-survey-philippine-business-and-industry). These publications provide control, privacy, evidence, and sector context. They do not evaluate Outsourced Employment or these synthetic cases.';
export const september14ResearchBatch:Sep14ResearchPost[]=studies.map(([slug,title,excerpt,image,question,method,measures,boundary,limits])=>({slug,title,excerpt,image,publishedDate:'2026-09-14',body:[`Research question: ${question}`,`Method: ${method}`,`Measures: Report ${measures}. Lock the classification and calculation rules before review.`,`Decision boundary: Reviewers identify evidence conditions. They do not ${boundary}.`,`Limitations: ${limits} A live pilot needs approved definitions, privacy review, an audit trail, and a stop condition.`,references]}));
