export type Sep3ResearchPost={slug:string;title:string;excerpt:string;publishedDate:'2026-09-03';body:string[]};
const date='2026-09-03' as const;
const sources='Sources consulted: NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework); FTC privacy and security guidance (https://www.ftc.gov/business-guidance/privacy-security); International Labour Organization decent-work resources (https://www.ilo.org/topics-and-sectors/decent-work); Philippine Statistics Authority Labor Force Survey (https://psa.gov.ph/statistics/labor-force-survey). These sources supply general governance, privacy, employment, and statistical context. They do not decide an employer policy, individual case, legal obligation, employment outcome, or provider result.';

const effectiveDateBody=[
'Research question: when several dated instructions affect the same Philippines employment record, which evidence allows an operations team to identify an effective-date collision without deciding which instruction should govern?',
'An effective-date collision occurs when documented events claim overlapping or incompatible effects for the same field. A manager request, HR approval, correction, system entry, and employee notice may all carry dates, but those dates describe different events. This study treats the collision as an evidence problem. It does not assume the newest message is authoritative or that the earliest effective date is correct. The employer\'s designated owner retains that decision.',
'Methodology: construct forty de-identified synthetic cases covering reporting-line changes, schedules, contact records, cost centers, leave status, payroll inputs, and access attributes. Each case contains an original state and at least two dated events. Vary arrival order, approval state, effective interval, source version, time zone, and whether the resulting system state is observable. Two reviewers independently reconstruct each chronology using a field dictionary fixed before review.',
'The unit is one field for one worker across one declared period. Reviewers record source identifier, source owner, request timestamp, approval event, stated effective date, entry timestamp, supersession link, notice event, observed result, and unresolved question. They classify collisions as overlapping approvals, correction without supersession, entry before authority, future instruction obscured by a later upload, inconsistent time-zone display, or unable to determine. These categories describe records rather than intent.',
'A reproducible chronology preserves original timestamps and provides one normalized reporting zone. Normalization must not overwrite the source value. A message sent late in Manila can appear on the prior calendar day elsewhere, creating an apparent sequence reversal. Reviewers record the conversion rule and test boundary cases separately. Location explains a clock display; it does not prove delay, consent, availability, or responsibility for a conflict.',
'Facts and analysis receive separate fields. A fact may be that approval A states September 8 and correction B states September 6. Analysis may identify an overlap and recommend owner review. The coordinator may assemble both sources, compare scope, and name downstream records that could be affected. The coordinator should not choose a governing date, change pay, interpret a contract, or notify the worker of an outcome before the authorized owner decides.',
'The primary measure is reconstructable collision rate: cases in which both competing instructions and their relationship can be independently followed. Secondary measures include reviewer agreement, missing-authority frequency, unresolved time-zone cases, downstream-state visibility, and the share of corrections with an explicit superseded-by reference. Unknown cases remain in the denominator. Removing them would make the workflow appear more reliable precisely where its evidence is weakest.',
'The study also tests a counterfactual register. Reviewers repeat a subset with a register that separates received, approved, effective, entered, communicated, and verified dates. Better reconstruction would support the register as an administrative control, not prove that the underlying decision was correct. If reviewers still disagree, the report identifies whether definitions, source authority, incomplete history, or a policy question caused the difference.',
'Privacy limits the packet. Use stable internal references, masked examples, restricted source links, and the minimum fields needed for the decision. A broad queue should show status and owner rather than copying personal documents. Access to a source is not implied by responsibility for a tracker. Missing access becomes a named constraint and routes to the data owner; it does not justify an informal copy.',
'External sources are deliberately bounded. General security guidance can inform evidence governance, while labor sources can explain why careful administration matters. None can validate an individual change or establish which instruction controls. Population statistics cannot substitute for an employer roster. Every claim from the experiment therefore stays tied to the synthetic cases, recorded fields, review rules, and observed reviewer decisions.',
'A correction creates a new event instead of erasing the prior instruction. The record links the correction to what it supersedes, identifies who authorized it, and shows whether downstream systems changed. When only part of an instruction changes, unchanged fields remain attached to their original authority. This design lets a later reviewer distinguish a clerical repair from a new employment decision without inventing history.',
'The review includes cases that appear conflict-free on first inspection. Reviewers check whether a single visible date has collapsed several events, whether an approval refers to the same source version, and whether a future instruction remains queued after a current change. This negative-case sampling matters because a collision register tested only on known failures cannot show whether its definitions create false alarms. Results report both detected collisions and clean cases, with the evidence used for either classification. A clean classification means no conflict was observed under the declared scope and cutoff. It does not prove that an undisclosed message or hidden downstream system contains no competing instruction.',
'Limitations: synthetic cases cannot reproduce every HR system, contract term, jurisdictional requirement, or informal conversation. Audit logs may omit edits, clocks may be system-generated, and a visible field may not show downstream propagation. Reviewer agreement can show that a method is repeatable, but it cannot establish fairness, legality, worker understanding, or the substantive accuracy of an owner\'s decision.',
'Evidence-led conclusion: an effective-date collision becomes reviewable when event type, source authority, original timestamp, stated effective date, approval, supersession, communication, and observed result remain distinct. The useful output is a narrow exception packet that says what conflicts and who must decide. Philippines employment-support staff can reconstruct and route evidence while the responsible owner retains employment authority.',sources];

const study=(slug:string,title:string,excerpt:string,question:string,subject:string,method:string,unit:string,states:string,boundary:string,limits:string):Sep3ResearchPost=>({slug,title,excerpt,publishedDate:date,body:[
question,
`${subject} This research evaluates administrative evidence, not worker performance, legal compliance, employment merit, or provider quality. A recorded state supports only the event it names. It cannot silently stand in for approval, resulting system state, employee understanding, or an owner decision.`,
`Methodology: ${method} The cases include ordinary paths, conflicting sources, missing events, duplicates, late changes, inaccessible systems, and unknown outcomes. Two reviewers work independently against definitions fixed before they inspect results, then record why their classifications differ.`,
`The observation unit is ${unit} Each row preserves its source, version, authority, effective time, observed time, responsible role, resulting state, exception, and verification limit. Stable identifiers link corrections without deleting the earlier event. Unknown records stay visible instead of being converted into a convenient pass or removed from the denominator.`,
`The state model distinguishes ${states} Each state has a written entry condition and a named next owner. A timestamp measures an event, not effort or intent. Original time zones remain alongside any normalized reporting time so a display conversion cannot rewrite the chronology.`,
`Facts and analysis are stored separately. A fact reports a source, event, or observed system state. Analysis may identify a mismatch, test an alternative treatment, or recommend owner review. It must not claim a cause that the record does not show. Reviewers preserve disagreement and the evidence needed to resolve it rather than averaging incompatible classifications.`,
`The primary measure is reproducibility: whether another reviewer reaches the same evidence status from the retained record. Secondary measures include missing-source frequency, reviewer agreement, unresolved-case age, post-state visibility, and the distribution of exception reasons. Counts always name their population and cutoff. Closure-only reporting is rejected because it hides the oldest open work.`,
`A sensitivity analysis repeats ambiguous cases under each documented treatment without selecting the governing answer. If the conclusion changes, the report says that the decision depends on unresolved authority. If it remains stable, the result supports robustness only for this sample. Neither outcome grants the support role authority to change an employment record or communicate a final decision.`,
`Role boundary: ${boundary} Support may organize sources, apply an approved codebook, prepare neutral questions, maintain the chronology, and verify observable results. The accountable HR, payroll, security, benefits, leave, legal, or management owner retains decisions within their remit.`,
`Privacy controls use synthetic values, masked identifiers, restricted source systems, and minimum necessary reporting. A coordinator records an evidence location instead of copying sensitive material into a broad tracker. Missing permission is documented and routed. It is never bypassed to improve a completion statistic. Small groups and rare exceptions are aggregated where disclosure risk remains.`,
`External evidence is contextual. NIST and FTC material can inform governance and data protection. ILO resources provide broad employment context, while Philippine Statistics Authority publications describe their own populations and methods. None validates a company record, establishes a service level, supplies an employer denominator, or resolves an individual employment question.`,
`Quality review samples both smooth cases and stopped cases. Easy cases test whether the process records ordinary completion; stopped cases test whether it names missing evidence and authority. Reviewers retain source snapshots and rule versions so later repetition can distinguish an improved record from a changed population, definition, system, or calendar.`,
`Negative-case testing is included for ${subject}. The sample selection rule is documented before any outcome is visible. Reviewers examine records expected to pass and records with seeded ambiguity, then report false alarms and missed conditions alongside successful classifications. A pass means the declared evidence supported the narrow state at the cutoff. It does not prove that hidden systems, later events, private communications, or facts outside scope would produce the same answer. This comparison keeps the method from being judged only on examples selected because they already contain a known defect.`,
`Limitations: ${limits} Synthetic evidence does not establish causation, fairness, staffing adequacy, security, legal sufficiency, employee understanding, or live-system accuracy. Platform events may be incomplete and reviewer agreement can reproduce a shared mistake. Findings apply only to the declared sample, definitions, cutoff, and available evidence.`,
`Evidence-led conclusion: ${subject} becomes defensible only when its population, source, authority, event sequence, exceptions, unknowns, and observed result remain inspectable. Philippines employment support can prepare that record and route the unresolved decision. The authorized owner decides the employment, payroll, access, leave, or communication consequence.`,sources]});

export const september3ResearchBatch:Sep3ResearchPost[]=[
{slug:'philippines-employment-effective-date-collision-study',title:'Philippines Employment Records: An Effective-Date Collision Study',excerpt:'A bounded study of conflicting request, approval, entry, and effective dates in distributed employment administration.',publishedDate:date,body:effectiveDateBody},
study('philippines-payroll-exception-aging-study','Philippines Payroll Support: An Exception-Aging Cohort Study','Research how payroll-input exceptions move through evidence, owner review, correction, and verification states.','Research question: can a Philippines payroll-support operation measure exception aging without confusing elapsed time with staff effort, decision delay, or payroll correctness?','Payroll exception aging','create fifty-four synthetic exceptions across time inputs, approved leave, worker data, allowances, deductions, new hires, terminations, and provider responses. Give every case immutable detection, evidence, review, submission, acceptance, comparison, reopening, and closure events.','one exception version in one detection cohort.','detected, waiting for evidence, ready for owner, returned, resubmitted, provider accepted, verified, withdrawn, duplicate, reopened, and unknown.','A coordinator may reconcile approved sources, maintain the ledger, request missing evidence, and prepare an owner packet, but cannot approve pay, alter entitlement, interpret tax or law, release funds, or promise a payment date.','The simulated cohort omits live payroll outcomes, local rules, provider internals, informal work, and many system behaviors.'),
study('philippines-onboarding-evidence-reviewer-agreement-study','Philippines Onboarding Evidence: A Reviewer-Agreement Study','A controlled test of whether two reviewers reach the same evidence status without assuming eligibility or approval.','Research question: when two Philippines onboarding-support reviewers examine the same packet, how consistently can they identify evidence status without deciding eligibility or employment terms?','Onboarding evidence review','assemble sixty synthetic packets spanning letters, acknowledgments, payroll forms, benefit elections, equipment, access approvals, and manager instructions. Vary missing pages, outdated templates, conflicting fields, unreadable files, excessive data, and wrong-recipient delivery.','one required-item check within one onboarding packet.','observed and usable, observed but defective, absent, not applicable under the approved scenario, conflicting, restricted, and unknown.','Reviewers may inventory, compare identifiers and versions, flag contradictions, and route missing items. They cannot decide eligibility, approve employment, interpret terms, validate identity, waive requirements, grant access, or change compensation.','Artificial packets, a fixed codebook, trained reviewers, review-order effects, and the absence of candidate understanding limit generalization.'),
study('philippines-leave-balance-provenance-reconstruction','Philippines Leave Records: Reconstructing Balance Provenance','Research whether a reported leave balance can be traced to dated events, approved rules, and observable results.','Research question: what evidence is required to reconstruct a Philippines employment leave balance without turning reconciliation into a decision about entitlement?','Leave-balance provenance','build forty-eight synthetic ledgers covering opening amounts, accruals, approved use, cancellations, carryover, retroactive corrections, duplicate imports, and delayed synchronization. Withhold one material item in selected cases to test whether reviewers preserve uncertainty.','one balance component for one worker and cutoff.','recorded, approved, pending, posted, reversed, excluded by cutoff, displayed, disputed, conflicting, and unknown.','A coordinator may log requests, calculate under an owner-approved rule, compare entries, and route a variance. They cannot approve leave, diagnose a condition, interpret a right, alter a balance without authority, or disclose a private reason.','Simplified rules, rounding, hidden system components, synthetic events, and no legal or policy assessment constrain the findings.'),
study('philippines-offboarding-access-closure-false-positive-study','Philippines Offboarding Access: A False-Closure Study','Test when closed tickets fail to prove that employment-related access was removed from each declared system.','Research question: how often can an offboarding access ticket appear closed while evidence remains insufficient to show that every declared permission was removed or transferred?','Offboarding access closure evidence','construct fifty synthetic cases across named accounts, groups, direct entitlements, shared mailboxes, files, tokens, physical access, and provider systems. Vary inherited access, failed automation, exceptions, transfers, unavailable exports, and reopened tickets.','one identity-access-system tuple at a declared cutoff.','requested, task complete, action logged, post-state observed, transferred, retained by approved exception, conflicting, unobservable, out of scope, and unknown.','Support may inventory systems, route approved actions, track exceptions, and verify visible states. It cannot decide that employment ended, disable access without authority, inspect unrelated activity, waive security, or declare an incident.','Incomplete inventories, delayed propagation, hidden sessions, provider attestations, shared identities, and synthetic architecture limit assurance.')
];
