export type Sep4ResearchPost={slug:string;title:string;excerpt:string;publishedDate:'2026-09-04';image:string;body:string[]};
const image='/aug23-research-heroes/philippines-employment-document-version-research.png';
const sources='Sources consulted: Google Search Central, Article structured data (https://developers.google.com/search/docs/appearance/structured-data/article); Google Search Central, canonical URLs (https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls); Sitemaps protocol (https://www.sitemaps.org/protocol.html); NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework). These sources provide general web and control concepts. They do not measure this site, guarantee indexing, certify content quality, or replace editorial, legal, or employment judgment.';
const study=(slug:string,title:string,excerpt:string,question:string,method:string,scope:string):Sep4ResearchPost=>({slug,title,excerpt,publishedDate:'2026-09-04',image,body:[`Research question: ${question}`,`Method: ${method} Preserve every failed, unavailable and ambiguous observation in the denominator, and record who reviewed it and when.`,`Analysis should separate prevention from detection and technical conformance from editorial quality. Report results by defect type rather than reducing unlike failures to one score.`,`Scope and limitations: ${scope} Synthetic cases, a narrow Philippines employment-operations vocabulary and one application architecture limit generalization. The study cannot establish legal obligations, search performance or provider quality.`,`The evidence can inform a publishing control, but the authorized editor retains claim and release decisions. A useful conclusion states what was observed, what remains unknown and which owner must resolve exceptions.`,sources]});
export const september4ResearchBatch:Sep4ResearchPost[]=[
study('philippines-daily-publishing-gate-reliability-research','Daily Publishing Gates: A Reliability Study for Philippines Content Operations','A reproducible test of whether staged editorial and technical gates expose defects before release.','Do staged brief, evidence, integration and live-review gates expose more defects than one final review?','Create forty synthetic article packages with seeded title, claim, date, canonical, image, index, sitemap and layout defects; assign half to each review condition.','The unit is one seeded defect in one article package, not an article count or reviewer-performance score.'),
study('philippines-article-identity-collision-research','Article Identity Collisions in a Focused Publishing Library','Test how slug, title, outline, and reader-outcome comparisons detect duplicates that exact matching misses.','Which identity fields best detect near-duplicate articles before publication?','Construct sixty pairs covering exact matches, revised slugs, similar titles, mirrored outlines, related Blog and Research pages and distinct controls; compare three blinded review cards.','The reference classification depends on editorial judgment and does not show how search engines evaluate similarity.'),
study('philippines-structured-date-consistency-research','Structured Publication Dates: Testing Cross-Surface Consistency','Measure whether one controlled date field keeps visible text, structured data, indexes, and campaign counts aligned.','How often does one controlled date field prevent disagreement across public article surfaces?','Render forty-eight synthetic routes using repeated manual dates, a shared field, or a shared field plus live extraction; seed stale values, locale shifts, omissions and prior-day defaults.','Compare intended ISO date with visible text, time markup, JSON-LD datePublished, index order and reported count for each route.'),
study('philippines-content-source-limitation-disclosure-research','Source-Limitation Disclosures in Employment Operations Content','Study whether claim-level limitation notes improve reviewers’ ability to spot conclusions that exceed the evidence.','Do explicit scope notes help editors identify conclusions that go beyond a cited source?','Prepare thirty-two matched passages using public standards, government guidance, country indicators and synthetic observations; show reviewers citations alone or citations with limitation notes.','Measure supported, qualified and unsupported classifications, agreement, review time and missed overclaims; confidence is not correctness.'),
study('philippines-live-route-audit-coverage-research','Live Route Audit Coverage After Batch Deployment','Compare sample-based and complete route checks for detecting release defects in a seventeen-article campaign.','What defect visibility is lost when a seventeen-route release is sampled rather than checked in full?','Create repeated synthetic batches with status, canonical, datePublished, visible date, image, family-index, sitemap and narrow-layout failures; compare four audit strategies.','The unit is one seeded route-gate failure. Complete checking reduces sampling risk but cannot prove prose accuracy, future availability or accessibility.')
];
