export type Sep8ResearchPost={slug:string;title:string;excerpt:string;publishedDate:'2026-09-08';image:string;body:string[]};

const sources='Sources consulted: NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework); NIST Privacy Framework (https://www.nist.gov/privacy-framework); U.S. Government Accountability Office, Standards for Internal Control in the Federal Government (https://www.gao.gov/products/gao-14-704g); Google Search Central, Article structured data (https://developers.google.com/search/docs/appearance/structured-data/article); Sitemaps protocol (https://www.sitemaps.org/protocol.html). These sources supply general control, privacy, and publishing concepts. They do not report results for Outsourced Employment, create legal or employment requirements, guarantee search indexing, or validate a live workflow.';
const study=(slug:string,title:string,excerpt:string,image:string,body:string[]):Sep8ResearchPost=>({slug,title,excerpt,publishedDate:'2026-09-08',image,body:[...body,sources]});

export const september8ResearchBatch:Sep8ResearchPost[]=[
study('philippines-employee-data-change-verification-research','Testing Verification Steps for Employee Data Changes','A bounded review of whether explicit identity and approval checks reduce unsafe updates in synthetic HR requests.','/aug20-research-heroes/philippines-employment-request-intake-research.webp',[
'Research question: Do explicit sender verification, field comparison, and owner approval steps reduce incorrect employee data changes compared with a general instruction to process complete requests?',
'Methodology: Create forty-eight synthetic change requests covering address, bank detail, contact, emergency contact, and name fields. Seed mismatched identifiers, copied messages, missing effective dates, unauthorized channels, conflicting records, and clean controls. Two reviewers assess every request in randomized order, first with the general instruction and later with the explicit checklist after a washout interval.',
'Scope and measures: The unit is one requested field change. Record incorrect approvals, correct holds, missed identity conflicts, owner escalations, reviewer agreement, and review time. Report bank-detail results separately because their risk and approval path differ from ordinary contact changes.',
'Inference limits: The comparison can show whether reviewers apply the test checklist consistently to the synthetic set. It cannot establish the identity of a real requester, the security of a live HR system, fraud prevalence, or the legal sufficiency of a company process.',
'Limitations and use: Seeded examples are smaller and cleaner than real case histories, and reviewers may remember some patterns despite randomized order. An HR or security owner could use the results to revise an intake checklist, but authorized owners retain verification, access, approval, and record-change decisions.'
]),
study('philippines-payroll-correction-review-research','Can Reviewers Reconstruct a Payroll Correction?','Test which packet fields help reviewers trace a proposed correction without relying on private chat history.','/aug21-research-heroes/philippines-employment-payroll-input-variance-research.png',[
'Research question: Which combination of source reference, prior value, proposed value, effective period, reason, and approval evidence lets a reviewer reconstruct a payroll correction?',
'Methodology: Build thirty-six de-identified correction packets with seeded missing sources, inconsistent periods, duplicate requests, unclear approvals, changed attachments, and clean controls. Assign packets across three conditions: request message only, basic cover sheet, or versioned evidence packet. Reviewers record whether they can trace and disposition each item.',
'Scope and measures: The unit is one correction packet. Measure successful reconstruction, missed conflicts, duplicate detection, correct approval identification, unresolved status, and review time. The study examines documentary traceability, not payroll calculation.',
'Inference limits: Better reconstruction in this set would support the tested packet design only. It would not prove wage compliance, tax treatment, payment accuracy, employee identity, or provider performance.',
'Limitations and use: De-identified packets omit some integration history and may make sources easier to compare. A payroll owner may use the results to choose required packet fields. Coordinators may assemble evidence, while authorized payroll and finance owners keep interpretation, approval, and release authority.'
]),
study('philippines-shared-mailbox-offboarding-research','Finding Orphaned Shared-Mailbox Access After Offboarding','A synthetic inventory study comparing ticket closure with direct checks of ownership, delegation, and routing.','/aug23-research-heroes/philippines-employment-access-review-evidence-research.png',[
'Research question: Does a direct inventory of mailbox owners, delegates, aliases, forwarding rules, and automated routing find unresolved access that a closed offboarding ticket misses?',
'Methodology: Construct twenty-eight synthetic offboarding cases across shared inbox patterns. Seed removed personal accounts with surviving delegation, ownerless mailboxes, stale forwarding, reassigned queues, closed tickets without evidence, and verified controls. Reviewers examine either the ticket record or the direct inventory, then compare dispositions.',
'Scope and measures: The unit is one mailbox access path. Count confirmed removals, false closures, orphaned ownership, unresolved routing, reviewer agreement, and review time by access type.',
'Inference limits: Results can compare the two review methods on the seeded cases. They cannot show that every account in a live environment has been discovered, that a vendor removed cached access, or that no message was retained elsewhere.',
'Limitations and use: Synthetic cases omit vendor-specific behavior, legal holds, incident response, and informal account sharing. Security and system owners may use the findings to set closure evidence. They still decide access, retention, investigation, and exceptions.'
]),
study('philippines-hr-request-duplicate-detection-research','When Are Two HR Requests Really the Same Case?','Evaluate whether a structured comparison reduces incorrect merges across sanitized request records.','/aug23-research-heroes/philippines-employment-document-version-research.png',[
'Research question: Can a comparison of verified sender, requested action, relevant date, attachment identity, and case reference distinguish true duplicate HR requests from related but separate requests?',
'Methodology: Prepare fifty pairs of sanitized requests. Include exact duplicates across channels, follow-ups with new evidence, similar topics for different employees, separate actions in one event, and deliberately ambiguous pairs. Reviewers classify the pairs with either subject-line matching or a structured comparison card.',
'Scope and measures: The unit is one request pair. Record incorrect merges, missed duplicates, sensitivity flags, correct escalation of ambiguity, reviewer agreement, and classification time. Preserve uncertain outcomes rather than forcing them into duplicate or separate.',
'Inference limits: Classification performance on prepared pairs does not estimate the frequency of duplicates in a real inbox. It also cannot establish employee identity, authorization, policy meaning, or whether two live cases may lawfully share access.',
'Limitations and use: Sanitization removes conversational nuance and may make identifiers unusually tidy. An HR operations owner can use the findings to refine linking rules. Case access, substantive responses, policy decisions, and uncertain merges remain with authorized HR staff.'
]),
study('philippines-onboarding-question-pattern-research','What First-Week Questions Reveal About an Onboarding Guide','A small study design for separating missing instructions from findability, access, and owner-response problems.','/aug21-research-heroes/philippines-employment-onboarding-evidence-research.png',[
'Research question: Can coded first-week questions identify whether a new hire was blocked by missing content, hard-to-find content, unavailable access, unclear ownership, or a case-specific decision?',
'Methodology: Create sixty sanitized question records tied to synthetic onboarding guides and access states. Seed correct but buried answers, outdated screenshots, missing steps, blocked accounts, policy questions, and complete guidance. Two reviewers code each record using a written taxonomy and document disagreements.',
'Scope and measures: The unit is one question record. Compare category agreement, source-link accuracy, correct owner routing, false claims that content is missing, and time to classification. Report access and policy questions separately from writing defects.',
'Inference limits: The study can test whether the taxonomy works on the prepared records. It cannot measure a real employee\'s learning, manager quality, psychological safety, or the effectiveness of an onboarding program.',
'Limitations and use: Synthetic questions lack tone and follow-up context, while a small sample limits generalization across roles. A process owner may use the results to prioritize guide repairs. HR, security, and business owners retain decisions about policy, access, employee support, and publication.'
])
];
